## Imported bindings main entry point — orchestrates the full generation
## pipeline: parses the policy, scans the raw module, generates lines, and
## assembles the final output source.

import std.string as string
import std.vec as vec
import std.fs as fs

import mtc.imported_bindings.policy as policy
import mtc.imported_bindings.raw_scanner as raw
import mtc.imported_bindings.emit as emit_mod


## Generate a complete imported binding module from a policy JSON file and
## a raw external module.  Returns the generated source as a string.String.
public function generate(
    policy_path: str,
    raw_module_path: str,
) -> Result[string.String, string.String]:
    # Parse the policy
    match policy.parse_policy(policy_path):
        Result.failure as p:
            return Result[string.String, string.String].failure(error = p.error)
        Result.success as p:
            var pol = p.value
            defer pol.release()

            # Read the raw module
            match fs.read_text(raw_module_path):
                Result.failure:
                    return Result[string.String, string.String].failure(
                        error = string.String.from_str("raw module read failed")
                    )
                Result.success as rp:
                    var raw_source = rp.value
                    defer raw_source.release()

                    # Scan the raw module
                    var raw_info = raw.scan_raw_module(raw_source.as_str())
                    defer raw_info.release()

                    # Build output
                    var result = string.String.with_capacity(4096)

                    # Header
                    result.append("# generated by mtc imported-bindings from ")
                    result.append(pol.raw_module_name.as_str())
                    result.append(" using ")
                    result.append(policy_path)
                    result.append("\n\n")
                    result.append("import ")
                    result.append(pol.raw_module_name.as_str())
                    result.append(" as ")
                    result.append(pol.import_alias.as_str())
                    result.append("\n")

                    # Cross-module imports from raw module (e.g. rl.Vector2 → import std.c.raylib as rl)
                    var cross_imports = emit_mod.collect_cross_module_imports(
                        raw_info.functions.as_span(),
                        raw_info.func_order.as_span(),
                        pol.functions,
                        raw_info.imports.as_span(),
                        pol.raw_module_name.as_str(),
                    )
                    var cx: ptr_uint = 0
                    while cx < cross_imports.len():
                        let il = cross_imports.get(cx)
                        if il != null:
                            result.append(unsafe: read(il).as_str())
                            result.append("\n")
                        cx += 1
                    release_string_vec(ref_of(cross_imports))

                    # Policy imports
                    var pii: ptr_uint = 0
                    while pii < pol.imports.len():
                        let imp = pol.imports.get(pii)
                        if imp != null:
                            result.append("import ")
                            result.append(unsafe: read(imp).module_name.as_str())
                            result.append(" as ")
                            result.append(unsafe: read(imp).alias.as_str())
                            result.append("\n")
                        pii += 1

                    # Type aliases
                    var type_lines = emit_mod.generate_type_lines(
                        raw_info.types.as_span(),
                        raw_info.type_order.as_span(),
                        pol.types,
                        pol.import_alias.as_str(),
                    )
                    if type_lines.len() > 0:
                        result.append("\n")
                        var ti: ptr_uint = 0
                        while ti < type_lines.len():
                            let line = type_lines.get(ti)
                            if line != null:
                                result.append(unsafe: read(line).as_str())
                                result.append("\n")
                            ti += 1
                    release_string_vec(ref_of(type_lines))

                    # Const aliases
                    var const_lines = emit_mod.generate_const_lines(
                        raw_info.consts.as_span(),
                        raw_info.const_order.as_span(),
                        pol.constants,
                        pol.import_alias.as_str(),
                    )
                    if const_lines.len() > 0:
                        result.append("\n")
                        var ci: ptr_uint = 0
                        while ci < const_lines.len():
                            let line = const_lines.get(ci)
                            if line != null:
                                result.append(unsafe: read(line).as_str())
                                result.append("\n")
                            ci += 1
                    release_string_vec(ref_of(const_lines))

                    # Foreign functions
                    var func_lines = emit_mod.generate_function_lines(
                        raw_info.functions.as_span(),
                        raw_info.func_order.as_span(),
                        pol.functions,
                        pol.import_alias.as_str(),
                    )
                    if func_lines.len() > 0:
                        result.append("\n")
                        var fi: ptr_uint = 0
                        while fi < func_lines.len():
                            let line = func_lines.get(fi)
                            if line != null:
                                result.append(unsafe: read(line).as_str())
                                result.append("\n")
                            fi += 1
                    release_string_vec(ref_of(func_lines))

                    return Result[string.String, string.String].success(value = result)


function release_string_vec(v: ref[vec.Vec[string.String]]) -> void:
    var i: ptr_uint = 0
    while i < v.len():
        let p = v.get(i)
        if p != null:
            unsafe: read(p).release()
        i += 1
    v.release()
