require 'rake/testtask'
require_relative 'lib/milk_tea'

RAYLIB_MODULE_NAME = 'std.c.raylib'
RAYLIB_BINDING_PATH = File.expand_path('std/c/raylib.mt', __dir__)
RAYLIB_INCLUDE_DIRECTIVES = ['raylib.h'].freeze
RAYLIB_LINK_LIBRARIES = ['raylib'].freeze
RAYLIB_HEADER_CANDIDATES = [
  '/usr/include/raylib.h',
  '/usr/local/include/raylib.h',
].freeze

task default: :test
task verify: [:test, 'bindgen:check_raylib']

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.pattern = 'test/**/*_test.rb'
end

namespace :bindgen do
  desc 'Regenerate std/c/raylib.mt from the installed raylib header'
  task :raylib do
    header_path = raylib_header_path
    generated = generate_raylib_binding(header_path)

    File.write(RAYLIB_BINDING_PATH, generated)
    puts "generated #{header_path} -> #{RAYLIB_BINDING_PATH}"
  end

  desc 'Check that std/c/raylib.mt matches current bindgen output'
  task :check_raylib do
    header_path = raylib_header_path
    expected = normalized_bindgen_output(File.read(RAYLIB_BINDING_PATH))
    actual = normalized_bindgen_output(generate_raylib_binding(header_path))

    if expected != actual
      raise <<~MESSAGE
        #{RAYLIB_BINDING_PATH} is out of date for #{header_path}
        Run `rake bindgen:raylib` to regenerate it.
      MESSAGE
    end

    puts "verified #{RAYLIB_BINDING_PATH} matches bindgen output from #{header_path}"
  end
end

def raylib_header_path
  env_override = ENV['RAYLIB_HEADER']
  candidates = []
  candidates << env_override unless env_override.nil? || env_override.empty?
  candidates.concat(RAYLIB_HEADER_CANDIDATES)

  header_path = candidates.find { |path| File.file?(path) }
  return header_path if header_path

  raise "raylib header not found; set RAYLIB_HEADER or install raylib headers"
end

def generate_raylib_binding(header_path)
  MilkTea::Bindgen.generate(
    module_name: RAYLIB_MODULE_NAME,
    header_path:,
    link_libraries: RAYLIB_LINK_LIBRARIES,
    include_directives: RAYLIB_INCLUDE_DIRECTIVES,
  )
end

def normalized_bindgen_output(source)
  source.sub(/\A# generated by mtc bindgen from .*\n/, "# generated by mtc bindgen from <header>\n")
end
