module examples.idiomatic.raylib.raw_data

import std.raylib as rl

const raw_width: i32 = 384
const raw_height: i32 = 512
const checked_width: i32 = 960
const checked_height: i32 = 480
const check_size: i32 = 32
const screen_width: i32 = 800
const screen_height: i32 = 450
const raw_image_path: str = "../../raylib/resources/fudesumi.raw"


def main() -> i32:
    rl.init_window(screen_width, screen_height, "Milk Tea Raw Texture Data")
    defer rl.close_window()

    let fudesumi_raw = rl.load_image_raw(raw_image_path, raw_width, raw_height, rl.PixelFormat.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 0)
    let fudesumi = rl.load_texture_from_image(fudesumi_raw)
    rl.unload_image(fudesumi_raw)

    let checked_image = rl.gen_image_checked(checked_width, checked_height, check_size, check_size, rl.ORANGE, rl.GOLD)
    let checked = rl.load_texture_from_image(checked_image)
    rl.unload_image(checked_image)

    defer:
        rl.unload_texture(checked)
        rl.unload_texture(fudesumi)

    rl.set_target_fps(60)

    while not rl.window_should_close():
        rl.begin_drawing()
        defer rl.end_drawing()

        rl.clear_background(rl.RAYWHITE)
        rl.draw_texture(checked, screen_width / 2 - checked.width / 2, screen_height / 2 - checked.height / 2, rl.fade(rl.WHITE, 0.5))
        rl.draw_texture(fudesumi, 430, -30, rl.WHITE)

        rl.draw_text("CHECKED TEXTURE ", 84, 85, 30, rl.BROWN)
        rl.draw_text("GENERATED by CODE", 72, 148, 30, rl.BROWN)
        rl.draw_text("and RAW IMAGE LOADING", 46, 210, 30, rl.BROWN)
        rl.draw_text("(c) Fudesumi sprite by Eiden Marsal", 310, screen_height - 20, 10, rl.BROWN)

    return 0
