# frozen_string_literal: true

require "tmpdir"
require_relative "../test_helper"

class MilkTeaStdOrderedMapTest < Minitest::Test
  def test_host_runtime_executes_ordered_map_operations
    compiler = ENV.fetch("CC", "cc")
    skip "C compiler not available: #{compiler}" unless compiler_available?(compiler)

    source = [
      "",
      "import std.ordered_map as ordered_map",
      "",
      "struct Key:",
      "    value: int",
      "",
      "extending Key:",
      "    static function order(left: const_ptr[Key], right: const_ptr[Key]) -> int:",
      "        unsafe:",
      "            return read(ptr[Key]<-left).value - read(ptr[Key]<-right).value",
      "",
      "function read_int(value: ptr[int]?) -> int:",
      "    if value == null:",
      "        return -1",
      "    unsafe:",
      "        return read(ptr[int]<-value)",
      "",
      "function main() -> int:",
      "    var values = ordered_map.OrderedMap[Key, int].create()",
      "    defer values.release()",
      "",
      "    if not values.is_empty():",
      "        return 1",
      "    if values.get(Key(value = 1)) != null:",
      "        return 2",
      "",
      "    let first_insert = values.set(Key(value = 3), 30)",
      "    match first_insert:",
      "        Option.none:",
      "            if false:",
      "                return 100",
      "        Option.some as ignored_payload:",
      "            return 3",
      "",
      "    values.set(Key(value = 1), 10)",
      "    values.set(Key(value = 4), 40)",
      "    values.set(Key(value = 2), 20)",
      "",
      "    if values.len() != 4:",
      "        return 4",
      "    if not values.contains(Key(value = 2)):",
      "        return 5",
      "    if read_int(values.get(Key(value = 4))) != 40:",
      "        return 6",
      "",
      "    let replaced = values.set(Key(value = 3), 31)",
      "    match replaced:",
      "        Option.none:",
      "            return 7",
      "        Option.some as payload:",
      "            if payload.value != 30:",
      "                return 8",
      "",
      "    let stored_key = values.get_key(Key(value = 2))",
      "    if stored_key == null:",
      "        return 9",
      "    unsafe:",
      "        if read(ptr[Key]<-stored_key).value != 2:",
      "            return 10",
      "",
      "    var expected_key = 1",
      "    var key_sum = 0",
      "    for key in values.keys():",
      "        unsafe:",
      "            let current = read(ptr[Key]<-key).value",
      "            if current != expected_key:",
      "                return 11",
      "            key_sum += current",
      "        expected_key += 1",
      "    if key_sum != 10:",
      "        return 12",
      "",
      "    var value_sum = 0",
      "    for value in values.values():",
      "        unsafe:",
      "            if read(value) == 20:",
      "                read(value) = 21",
      "            value_sum += read(value)",
      "    if value_sum != 102:",
      "        return 13",
      "",
      "    var entry_total = 0",
      "    for entry in values:",
      "        unsafe:",
      "            let current_key = read(ptr[Key]<-entry.key).value",
      "            if current_key == 4:",
      "                read(entry.value) = 41",
      "            entry_total += current_key",
      "            entry_total += read(entry.value)",
      "    if entry_total != 113:",
      "        return 14",
      "",
      "    var current_total = 0",
      "    var current_key = 1",
      "    var entries = values.entries()",
      "    while entries.next():",
      "        let entry = entries.current()",
      "        unsafe:",
      "            let key_value = read(ptr[Key]<-entry.key).value",
      "            if key_value != current_key:",
      "                return 15",
      "            current_total += key_value",
      "            current_total += read(entry.value)",
      "        current_key += 1",
      "    if current_total != 113:",
      "        return 16",
      "",
      "    let inserted_ptr = values.get_or_insert(Key(value = 5), 50)",
      "    unsafe:",
      "        if read(inserted_ptr) != 50:",
      "            return 17",
      "        read(inserted_ptr) = 51",
      "",
      "    let existing_ptr = values.get_or_insert(Key(value = 4), 99)",
      "    unsafe:",
      "        if read(existing_ptr) != 41:",
      "            return 18",
      "",
      "    let removed = values.remove_entry(Key(value = 3))",
      "    match removed:",
      "        Option.none:",
      "            return 19",
      "        Option.some as payload:",
      "            if payload.value.key.value != 3:",
      "                return 20",
      "            if payload.value.value != 31:",
      "                return 21",
      "",
      "    if values.contains(Key(value = 3)):",
      "        return 22",
      "    if values.len() != 4:",
      "        return 23",
      "    if read_int(values.get(Key(value = 5))) != 51:",
      "        return 24",
      "",
      "    var previous = 0",
      "    var total = 0",
      "    for entry in values:",
      "        unsafe:",
      "            let current = read(ptr[Key]<-entry.key).value",
      "            if current <= previous:",
      "                return 25",
      "            previous = current",
      "            total += current",
      "            total += read(entry.value)",
      "    if total != 135:",
      "        return 26",
      "",
      "    let removed_value = values.remove(Key(value = 4))",
      "    match removed_value:",
      "        Option.none:",
      "            return 27",
      "        Option.some as payload:",
      "            if payload.value != 41:",
      "                return 28",
      "",
      "    let missing = values.remove(Key(value = 3))",
      "    match missing:",
      "        Option.none:",
      "            if false:",
      "                return 101",
      "        Option.some as ignored_payload:",
      "            return 29",
      "",
      "    values.clear()",
      "    if not values.is_empty():",
      "        return 30",
      "    if values.get(Key(value = 1)) != null:",
      "        return 31",
      "    return 0",
      "",
    ].join("\n")

    result = run_program(source, compiler:)

    assert_equal "", result.stdout
    assert_equal "", result.stderr
    assert_equal 0, result.exit_status
    assert_equal [], result.link_flags
  end

  private

  def run_program(source, compiler:)
    Dir.mktmpdir("milk-tea-std-ordered-map") do |dir|
      source_path = File.join(dir, "program.mt")
      File.write(source_path, source)
      return MilkTea::Run.run(source_path, cc: compiler)
    end
  end

  def compiler_available?(compiler)
    return File.executable?(compiler) if compiler.include?(File::SEPARATOR)

    ENV.fetch("PATH", "").split(File::PATH_SEPARATOR).any? do |entry|
      candidate = File.join(entry, compiler)
      File.file?(candidate) && File.executable?(candidate)
    end
  end
end
