# frozen_string_literal: true

require "tmpdir"
require_relative "../test_helper"

class MilkTeaStdNetTest < Minitest::Test
  def test_host_runtime_resolves_numeric_ipv4_and_formats_host
    compiler = ENV.fetch("CC", "cc")
    skip "C compiler not available: #{compiler}" unless compiler_available?(compiler)

    source = [
      "import std.async as aio",
      "import std.net as net",
      "import std.status as status",
      "",
      "async function main() -> int:",
      "    let resolved = await net.resolve_first(\"127.0.0.1\", \"8080\")",
      "    match resolved:",
      "        status.Status.err as payload:",
      "            var error = payload.error",
      "            defer error.release()",
      "            return 1",
      "        status.Status.ok as payload:",
      "            var address = payload.value",
      "            defer address.release()",
      "            match address.host():",
      "                status.Status.err as host_error_payload:",
      "                    var error = host_error_payload.error",
      "                    defer error.release()",
      "                    return 2",
      "                status.Status.ok as host_payload:",
      "                    var host = host_payload.value",
      "                    defer host.release()",
      "                    if host.as_str() != \"127.0.0.1\":",
      "                        return 3",
      "                    return 0",
      "",
    ].join("\n")

    result = run_program(source, compiler:)

    assert_equal "", result.stdout
    assert_equal "", result.stderr
    assert_equal 0, result.exit_status
    assert_includes result.link_flags, "-luv"
  end

  def test_host_runtime_constructs_literal_ipv6_address
    compiler = ENV.fetch("CC", "cc")
    skip "C compiler not available: #{compiler}" unless compiler_available?(compiler)

    source = [
      "import std.net as net",
      "import std.status as status",
      "",
      "async function main() -> int:",
      "    match net.ipv6(\"::1\", 443):",
      "        status.Status.err as payload:",
      "            var error = payload.error",
      "            defer error.release()",
      "            return 1",
      "        status.Status.ok as payload:",
      "            var address = payload.value",
      "            defer address.release()",
      "            match address.host():",
      "                status.Status.err as host_error_payload:",
      "                    var error = host_error_payload.error",
      "                    defer error.release()",
      "                    return 2",
      "                status.Status.ok as host_payload:",
      "                    var host = host_payload.value",
      "                    defer host.release()",
      "                    if host.as_str() != \"::1\":",
      "                        return 3",
      "                    return 0",
      "",
    ].join("\n")

    result = run_program(source, compiler:)

    assert_equal "", result.stdout
    assert_equal "", result.stderr
    assert_equal 0, result.exit_status
    assert_includes result.link_flags, "-luv"
  end

  def test_tcp_runtime_connects_and_accepts_local_listener
    compiler = ENV.fetch("CC", "cc")
    skip "C compiler not available: #{compiler}" unless compiler_available?(compiler)

    source = [
      "import std.async as aio",
      "import std.net as net",
      "import std.status as status",
      "",
      "function expect_host(address_result: status.Status[net.SocketAddress, net.Error], expected: str, failure_code: int) -> int:",
      "    match address_result:",
      "        status.Status.err as payload:",
      "            var error = payload.error",
      "            defer error.release()",
      "            return failure_code",
      "        status.Status.ok as payload:",
      "            var address = payload.value",
      "            defer address.release()",
      "            match address.host():",
      "                status.Status.err as host_error_payload:",
      "                    var error = host_error_payload.error",
      "                    defer error.release()",
      "                    return failure_code + 1",
      "                status.Status.ok as host_payload:",
      "                    var host = host_payload.value",
      "                    defer host.release()",
      "                    if host.as_str() != expected:",
      "                        return failure_code + 2",
      "                    return 0",
      "",
      "async function main() -> int:",
      "    match net.ipv4(\"127.0.0.1\", 0):",
      "        status.Status.err as payload:",
      "            var error = payload.error",
      "            defer error.release()",
      "            return 1",
      "        status.Status.ok as payload:",
      "            var bind_address = payload.value",
      "            defer bind_address.release()",
      "            match net.listen(bind_address, 16):",
      "                status.Status.err as listen_error_payload:",
      "                    var error = listen_error_payload.error",
      "                    defer error.release()",
      "                    return 2",
      "                status.Status.ok as listen_payload:",
      "                    var listener = listen_payload.value",
      "                    defer listener.release()",
      "                    match listener.local_address():",
      "                        status.Status.err as local_error_payload:",
      "                            var error = local_error_payload.error",
      "                            defer error.release()",
      "                            return 3",
      "                        status.Status.ok as local_payload:",
      "                            var local_address = local_payload.value",
      "                            defer local_address.release()",
      "                            let connected = await net.connect(local_address)",
      "                            match connected:",
      "                                status.Status.err as connect_error_payload:",
      "                                    var error = connect_error_payload.error",
      "                                    defer error.release()",
      "                                    return 4",
      "                                status.Status.ok as connect_payload:",
      "                                    var client = connect_payload.value",
      "                                    defer client.release()",
      "                                    let accepted = await listener.accept()",
      "                                    match accepted:",
      "                                        status.Status.err as accept_error_payload:",
      "                                            var error = accept_error_payload.error",
      "                                            defer error.release()",
      "                                            return 5",
      "                                        status.Status.ok as accept_payload:",
      "                                            var server = accept_payload.value",
      "                                            defer server.release()",
      "                                            let client_peer_status = expect_host(client.peer_address(), \"127.0.0.1\", 6)",
      "                                            if client_peer_status != 0:",
      "                                                return client_peer_status",
      "                                            let server_peer_status = expect_host(server.peer_address(), \"127.0.0.1\", 9)",
      "                                            if server_peer_status != 0:",
      "                                                return server_peer_status",
      "                                            let server_local_status = expect_host(server.local_address(), \"127.0.0.1\", 12)",
      "                                            if server_local_status != 0:",
      "                                                return server_local_status",
      "                                            return 0",
      "",
    ].join("\n")

    result = run_program(source, compiler:)

    assert_equal "", result.stdout
    assert_equal "", result.stderr
    assert_equal 0, result.exit_status
    assert_includes result.link_flags, "-luv"
  end

  def test_tcp_runtime_writes_reads_and_shutdowns
    compiler = ENV.fetch("CC", "cc")
    skip "C compiler not available: #{compiler}" unless compiler_available?(compiler)

    source = [
      "import std.bytes as bytes",
      "import std.maybe as maybe",
      "import std.net as net",
      "import std.status as status",
      "import std.str as text",
      "",
      "function expect_utf8_bytes(value: bytes.Bytes, expected: str, failure_code: int) -> int:",
      "    match value.as_str():",
      "        maybe.Maybe.none:",
      "            return failure_code",
      "        maybe.Maybe.some as payload:",
      "            if not payload.value.equal(expected):",
      "                return failure_code + 1",
      "            return 0",
      "",
      "async function main() -> int:",
      "    match net.ipv4(\"127.0.0.1\", 0):",
      "        status.Status.err as payload:",
      "            var error = payload.error",
      "            defer error.release()",
      "            return 1",
      "        status.Status.ok as payload:",
      "            var bind_address = payload.value",
      "            defer bind_address.release()",
      "            match net.listen(bind_address, 16):",
      "                status.Status.err as listen_error_payload:",
      "                    var error = listen_error_payload.error",
      "                    defer error.release()",
      "                    return 2",
      "                status.Status.ok as listen_payload:",
      "                    var listener = listen_payload.value",
      "                    defer listener.release()",
      "                    match listener.local_address():",
      "                        status.Status.err as local_error_payload:",
      "                            var error = local_error_payload.error",
      "                            defer error.release()",
      "                            return 3",
      "                        status.Status.ok as local_payload:",
      "                            var local_address = local_payload.value",
      "                            defer local_address.release()",
      "                            let pending_accept = listener.accept()",
      "                            let connected = await net.connect(local_address)",
      "                            match connected:",
      "                                status.Status.err as connect_error_payload:",
      "                                    var error = connect_error_payload.error",
      "                                    defer error.release()",
      "                                    return 4",
      "                                status.Status.ok as connect_payload:",
      "                                    var client = connect_payload.value",
      "                                    defer client.release()",
      "                                    let accepted = await pending_accept",
      "                                    match accepted:",
      "                                        status.Status.err as accept_error_payload:",
      "                                            var error = accept_error_payload.error",
      "                                            defer error.release()",
      "                                            return 5",
      "                                        status.Status.ok as accept_payload:",
      "                                            var server = accept_payload.value",
      "                                            defer server.release()",
      "                                            let pending_read = server.read_once(4096)",
      "                                            let write_result = await client.write_bytes(text.as_byte_span(\"ping\"))",
      "                                            match write_result:",
      "                                                status.Status.err as write_error_payload:",
      "                                                    var error = write_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 6",
      "                                                status.Status.ok as write_payload:",
      "                                                    if write_payload.value != 4:",
      "                                                        return 7",
      "                                            let read_result = await pending_read",
      "                                            match read_result:",
      "                                                status.Status.err as read_error_payload:",
      "                                                    var error = read_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 8",
      "                                                status.Status.ok as read_payload:",
      "                                                    var body = read_payload.value",
      "                                                    defer body.release()",
      "                                                    let body_status = expect_utf8_bytes(body, \"ping\", 9)",
      "                                                    if body_status != 0:",
      "                                                        return body_status",
      "                                            let shutdown_result = await client.shutdown()",
      "                                            match shutdown_result:",
      "                                                status.Status.err as shutdown_error_payload:",
      "                                                    var error = shutdown_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 11",
      "                                                status.Status.ok as shutdown_payload:",
      "                                                    if not shutdown_payload.value:",
      "                                                        return 12",
      "                                            let eof_result = await server.read_once(4096)",
      "                                            match eof_result:",
      "                                                status.Status.err as eof_error_payload:",
      "                                                    var error = eof_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 13",
      "                                                status.Status.ok as eof_payload:",
      "                                                    var eof_body = eof_payload.value",
      "                                                    defer eof_body.release()",
      "                                                    if eof_body.len != 0:",
      "                                                        return 14",
      "                                            return 0",
      "",
    ].join("\n")

    result = run_program(source, compiler:)

    assert_equal "", result.stdout
    assert_equal "", result.stderr
    assert_equal 0, result.exit_status
    assert_includes result.link_flags, "-luv"
  end

  def test_tcp_runtime_reads_exactly_across_multiple_writes
    compiler = ENV.fetch("CC", "cc")
    skip "C compiler not available: #{compiler}" unless compiler_available?(compiler)

    source = [
      "import std.bytes as bytes",
      "import std.maybe as maybe",
      "import std.net as net",
      "import std.status as status",
      "import std.str as text",
      "",
      "function expect_utf8_bytes(value: bytes.Bytes, expected: str, failure_code: int) -> int:",
      "    match value.as_str():",
      "        maybe.Maybe.none:",
      "            return failure_code",
      "        maybe.Maybe.some as payload:",
      "            if not payload.value.equal(expected):",
      "                return failure_code + 1",
      "            return 0",
      "",
      "async function main() -> int:",
      "    match net.ipv4(\"127.0.0.1\", 0):",
      "        status.Status.err as payload:",
      "            var error = payload.error",
      "            defer error.release()",
      "            return 1",
      "        status.Status.ok as payload:",
      "            var bind_address = payload.value",
      "            defer bind_address.release()",
      "            match net.listen(bind_address, 16):",
      "                status.Status.err as listen_error_payload:",
      "                    var error = listen_error_payload.error",
      "                    defer error.release()",
      "                    return 2",
      "                status.Status.ok as listen_payload:",
      "                    var listener = listen_payload.value",
      "                    defer listener.release()",
      "                    match listener.local_address():",
      "                        status.Status.err as local_error_payload:",
      "                            var error = local_error_payload.error",
      "                            defer error.release()",
      "                            return 3",
      "                        status.Status.ok as local_payload:",
      "                            var local_address = local_payload.value",
      "                            defer local_address.release()",
      "                            let pending_accept = listener.accept()",
      "                            let connected = await net.connect(local_address)",
      "                            match connected:",
      "                                status.Status.err as connect_error_payload:",
      "                                    var error = connect_error_payload.error",
      "                                    defer error.release()",
      "                                    return 4",
      "                                status.Status.ok as connect_payload:",
      "                                    var client = connect_payload.value",
      "                                    defer client.release()",
      "                                    let accepted = await pending_accept",
      "                                    match accepted:",
      "                                        status.Status.err as accept_error_payload:",
      "                                            var error = accept_error_payload.error",
      "                                            defer error.release()",
      "                                            return 5",
      "                                        status.Status.ok as accept_payload:",
      "                                            var server = accept_payload.value",
      "                                            defer server.release()",
      "                                            let pending_read = server.read_exactly(8)",
      "                                            let first_write = await client.write_bytes(text.as_byte_span(\"ping\"))",
      "                                            match first_write:",
      "                                                status.Status.err as write_error_payload:",
      "                                                    var error = write_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 6",
      "                                                status.Status.ok as write_payload:",
      "                                                    if write_payload.value != 4:",
      "                                                        return 7",
      "                                            let second_write = await client.write_bytes(text.as_byte_span(\"pong\"))",
      "                                            match second_write:",
      "                                                status.Status.err as write_error_payload:",
      "                                                    var error = write_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 8",
      "                                                status.Status.ok as write_payload:",
      "                                                    if write_payload.value != 4:",
      "                                                        return 9",
      "                                            let read_result = await pending_read",
      "                                            match read_result:",
      "                                                status.Status.err as read_error_payload:",
      "                                                    var error = read_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 10",
      "                                                status.Status.ok as read_payload:",
      "                                                    var body = read_payload.value",
      "                                                    defer body.release()",
      "                                                    let body_status = expect_utf8_bytes(body, \"pingpong\", 11)",
      "                                                    if body_status != 0:",
      "                                                        return body_status",
      "                                            return 0",
      "",
    ].join("\n")

    result = run_program(source, compiler:)

    assert_equal "", result.stdout
    assert_equal "", result.stderr
    assert_equal 0, result.exit_status
    assert_includes result.link_flags, "-luv"
  end

  def test_udp_runtime_sends_and_receives_datagrams
    compiler = ENV.fetch("CC", "cc")
    skip "C compiler not available: #{compiler}" unless compiler_available?(compiler)

    source = [
      "import std.bytes as bytes",
      "import std.maybe as maybe",
      "import std.net as net",
      "import std.status as status",
      "import std.str as text",
      "",
      "function expect_utf8_bytes(value: bytes.Bytes, expected: str, failure_code: int) -> int:",
      "    match value.as_str():",
      "        maybe.Maybe.none:",
      "            return failure_code",
      "        maybe.Maybe.some as payload:",
      "            if not payload.value.equal(expected):",
      "                return failure_code + 1",
      "            return 0",
      "",
      "async function main() -> int:",
      "    match net.ipv4(\"127.0.0.1\", 0):",
      "        status.Status.err as payload:",
      "            var error = payload.error",
      "            defer error.release()",
      "            return 1",
      "        status.Status.ok as receiver_address_payload:",
      "            var receiver_address = receiver_address_payload.value",
      "            defer receiver_address.release()",
      "            match net.ipv4(\"127.0.0.1\", 0):",
      "                status.Status.err as payload:",
      "                    var error = payload.error",
      "                    defer error.release()",
      "                    return 2",
      "                status.Status.ok as sender_address_payload:",
      "                    var sender_address = sender_address_payload.value",
      "                    defer sender_address.release()",
      "                    match net.udp_bind(receiver_address):",
      "                        status.Status.err as bind_error_payload:",
      "                            var error = bind_error_payload.error",
      "                            defer error.release()",
      "                            return 3",
      "                        status.Status.ok as receiver_payload:",
      "                            var receiver = receiver_payload.value",
      "                            defer receiver.release()",
      "                            match net.udp_bind(sender_address):",
      "                                status.Status.err as bind_error_payload:",
      "                                    var error = bind_error_payload.error",
      "                                    defer error.release()",
      "                                    return 4",
      "                                status.Status.ok as sender_payload:",
      "                                    var sender = sender_payload.value",
      "                                    defer sender.release()",
      "                                    match receiver.local_address():",
      "                                        status.Status.err as local_error_payload:",
      "                                            var error = local_error_payload.error",
      "                                            defer error.release()",
      "                                            return 5",
      "                                        status.Status.ok as local_payload:",
      "                                            var receiver_local = local_payload.value",
      "                                            defer receiver_local.release()",
      "                                            let pending_receive = receiver.recv_from(4096)",
      "                                            let send_result = await sender.send_to(text.as_byte_span(\"pong\"), receiver_local)",
      "                                            match send_result:",
      "                                                status.Status.err as send_error_payload:",
      "                                                    var error = send_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 6",
      "                                                status.Status.ok as send_payload:",
      "                                                    if send_payload.value != 4:",
      "                                                        return 7",
      "                                            let receive_result = await pending_receive",
      "                                            match receive_result:",
      "                                                status.Status.err as receive_error_payload:",
      "                                                    var error = receive_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 8",
      "                                                status.Status.ok as receive_payload:",
      "                                                    var datagram = receive_payload.value",
      "                                                    defer datagram.release()",
      "                                                    let body_status = expect_utf8_bytes(datagram.data, \"pong\", 9)",
      "                                                    if body_status != 0:",
      "                                                        return body_status",
      "                                                    match datagram.source.host():",
      "                                                        status.Status.err as host_error_payload:",
      "                                                            var error = host_error_payload.error",
      "                                                            defer error.release()",
      "                                                            return 11",
      "                                                        status.Status.ok as host_payload:",
      "                                                            var host = host_payload.value",
      "                                                            defer host.release()",
      "                                                            if host.as_str() != \"127.0.0.1\":",
      "                                                                return 12",
      "                                                    return 0",
      "",
    ].join("\n")

    result = run_program(source, compiler:)

    assert_equal "", result.stdout
    assert_equal "", result.stderr
    assert_equal 0, result.exit_status
    assert_includes result.link_flags, "-luv"
  end

  def test_udp_runtime_connects_and_reports_peer_address
    compiler = ENV.fetch("CC", "cc")
    skip "C compiler not available: #{compiler}" unless compiler_available?(compiler)

    source = [
      "import std.net as net",
      "import std.status as status",
      "",
      "function expect_host(address_result: status.Status[net.SocketAddress, net.Error], expected: str, failure_code: int) -> int:",
      "    match address_result:",
      "        status.Status.err as payload:",
      "            var error = payload.error",
      "            defer error.release()",
      "            return failure_code",
      "        status.Status.ok as payload:",
      "            var address = payload.value",
      "            defer address.release()",
      "            match address.host():",
      "                status.Status.err as host_error_payload:",
      "                    var error = host_error_payload.error",
      "                    defer error.release()",
      "                    return failure_code + 1",
      "                status.Status.ok as host_payload:",
      "                    var host = host_payload.value",
      "                    defer host.release()",
      "                    if host.as_str() != expected:",
      "                        return failure_code + 2",
      "                    return 0",
      "",
      "async function main() -> int:",
      "    match net.ipv4(\"127.0.0.1\", 0):",
      "        status.Status.err as payload:",
      "            var error = payload.error",
      "            defer error.release()",
      "            return 1",
      "        status.Status.ok as receiver_address_payload:",
      "            var receiver_address = receiver_address_payload.value",
      "            defer receiver_address.release()",
      "            match net.ipv4(\"127.0.0.1\", 0):",
      "                status.Status.err as payload:",
      "                    var error = payload.error",
      "                    defer error.release()",
      "                    return 2",
      "                status.Status.ok as sender_address_payload:",
      "                    var sender_address = sender_address_payload.value",
      "                    defer sender_address.release()",
      "                    match net.udp_bind(receiver_address):",
      "                        status.Status.err as bind_error_payload:",
      "                            var error = bind_error_payload.error",
      "                            defer error.release()",
      "                            return 3",
      "                        status.Status.ok as receiver_payload:",
      "                            var receiver = receiver_payload.value",
      "                            defer receiver.release()",
      "                            match net.udp_bind(sender_address):",
      "                                status.Status.err as bind_error_payload:",
      "                                    var error = bind_error_payload.error",
      "                                    defer error.release()",
      "                                    return 4",
      "                                status.Status.ok as sender_payload:",
      "                                    var sender = sender_payload.value",
      "                                    defer sender.release()",
      "                                    match receiver.local_address():",
      "                                        status.Status.err as local_error_payload:",
      "                                            var error = local_error_payload.error",
      "                                            defer error.release()",
      "                                            return 5",
      "                                        status.Status.ok as local_payload:",
      "                                            var receiver_local = local_payload.value",
      "                                            defer receiver_local.release()",
      "                                            match sender.connect(receiver_local):",
      "                                                status.Status.err as connect_error_payload:",
      "                                                    var error = connect_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 6",
      "                                                status.Status.ok as connect_payload:",
      "                                                    if not connect_payload.value:",
      "                                                        return 7",
      "                                            let peer_status = expect_host(sender.peer_address(), \"127.0.0.1\", 8)",
      "                                            if peer_status != 0:",
      "                                                return peer_status",
      "                                            return 0",
      "",
    ].join("\n")

    result = run_program(source, compiler:)

    assert_equal "", result.stdout
    assert_equal "", result.stderr
    assert_equal 0, result.exit_status
    assert_includes result.link_flags, "-luv"
  end

  def test_udp_runtime_connected_send_and_recv
    compiler = ENV.fetch("CC", "cc")
    skip "C compiler not available: #{compiler}" unless compiler_available?(compiler)

    source = [
      "import std.bytes as bytes",
      "import std.maybe as maybe",
      "import std.net as net",
      "import std.status as status",
      "import std.str as text",
      "",
      "function expect_utf8_bytes(value: bytes.Bytes, expected: str, failure_code: int) -> int:",
      "    match value.as_str():",
      "        maybe.Maybe.none:",
      "            return failure_code",
      "        maybe.Maybe.some as payload:",
      "            if not payload.value.equal(expected):",
      "                return failure_code + 1",
      "            return 0",
      "",
      "async function main() -> int:",
      "    match net.ipv4(\"127.0.0.1\", 0):",
      "        status.Status.err as payload:",
      "            var error = payload.error",
      "            defer error.release()",
      "            return 1",
      "        status.Status.ok as receiver_address_payload:",
      "            var receiver_address = receiver_address_payload.value",
      "            defer receiver_address.release()",
      "            match net.ipv4(\"127.0.0.1\", 0):",
      "                status.Status.err as payload:",
      "                    var error = payload.error",
      "                    defer error.release()",
      "                    return 2",
      "                status.Status.ok as sender_address_payload:",
      "                    var sender_address = sender_address_payload.value",
      "                    defer sender_address.release()",
      "                    match net.udp_bind(receiver_address):",
      "                        status.Status.err as bind_error_payload:",
      "                            var error = bind_error_payload.error",
      "                            defer error.release()",
      "                            return 3",
      "                        status.Status.ok as receiver_payload:",
      "                            var receiver = receiver_payload.value",
      "                            defer receiver.release()",
      "                            match net.udp_bind(sender_address):",
      "                                status.Status.err as bind_error_payload:",
      "                                    var error = bind_error_payload.error",
      "                                    defer error.release()",
      "                                    return 4",
      "                                status.Status.ok as sender_payload:",
      "                                    var sender = sender_payload.value",
      "                                    defer sender.release()",
      "                                    match receiver.local_address():",
      "                                        status.Status.err as local_error_payload:",
      "                                            var error = local_error_payload.error",
      "                                            defer error.release()",
      "                                            return 5",
      "                                        status.Status.ok as receiver_local_payload:",
      "                                            var receiver_local = receiver_local_payload.value",
      "                                            defer receiver_local.release()",
      "                                            match sender.local_address():",
      "                                                status.Status.err as local_error_payload:",
      "                                                    var error = local_error_payload.error",
      "                                                    defer error.release()",
      "                                                    return 6",
      "                                                status.Status.ok as sender_local_payload:",
      "                                                    var sender_local = sender_local_payload.value",
      "                                                    defer sender_local.release()",
      "                                                    match receiver.connect(sender_local):",
      "                                                        status.Status.err as connect_error_payload:",
      "                                                            var error = connect_error_payload.error",
      "                                                            defer error.release()",
      "                                                            return 7",
      "                                                        status.Status.ok as connect_payload:",
      "                                                            if not connect_payload.value:",
      "                                                                return 8",
      "                                                    match sender.connect(receiver_local):",
      "                                                        status.Status.err as connect_error_payload:",
      "                                                            var error = connect_error_payload.error",
      "                                                            defer error.release()",
      "                                                            return 9",
      "                                                        status.Status.ok as connect_payload:",
      "                                                            if not connect_payload.value:",
      "                                                                return 10",
      "                                                    let pending_receive = receiver.recv(4096)",
      "                                                    let send_result = await sender.send(text.as_byte_span(\"pong\"))",
      "                                                    match send_result:",
      "                                                        status.Status.err as send_error_payload:",
      "                                                            var error = send_error_payload.error",
      "                                                            defer error.release()",
      "                                                            return 11",
      "                                                        status.Status.ok as send_payload:",
      "                                                            if send_payload.value != 4:",
      "                                                                return 12",
      "                                                    let receive_result = await pending_receive",
      "                                                    match receive_result:",
      "                                                        status.Status.err as receive_error_payload:",
      "                                                            var error = receive_error_payload.error",
      "                                                            defer error.release()",
      "                                                            return 13",
      "                                                        status.Status.ok as receive_payload:",
      "                                                            var body = receive_payload.value",
      "                                                            defer body.release()",
      "                                                            let body_status = expect_utf8_bytes(body, \"pong\", 14)",
      "                                                            if body_status != 0:",
      "                                                                return body_status",
      "                                                    return 0",
      "",
    ].join("\n")

    result = run_program(source, compiler:)

    assert_equal "", result.stdout
    assert_equal "", result.stderr
    assert_equal 0, result.exit_status
    assert_includes result.link_flags, "-luv"
  end

  private

  def run_program(source, compiler:)
    Dir.mktmpdir("milk-tea-std-net") do |dir|
      source_path = File.join(dir, "program.mt")
      File.write(source_path, source)
      return MilkTea::Run.run(source_path, cc: compiler)
    end
  end

  def compiler_available?(compiler)
    return File.executable?(compiler) if compiler.include?(File::SEPARATOR)

    ENV.fetch("PATH", "").split(File::PATH_SEPARATOR).any? do |entry|
      candidate = File.join(entry, compiler)
      File.file?(candidate) && File.executable?(candidate)
    end
  end
end
