## Test runner — collects and runs all lexer and parser tests.

import std.testing as t
import test.lexer_test as lex_tests
import test.parser_test as parse_tests

public function run_all() -> int:
    var stats = t.Stats.create()

    stats = t.record(stats, "keywords_are_recognized", lex_tests.test_keywords_are_recognized())
    stats = t.record(stats, "bool_and_null_literals", lex_tests.test_bool_and_null_literals())
    stats = t.record(stats, "integer_literals", lex_tests.test_integer_literals())
    stats = t.record(stats, "float_literals", lex_tests.test_float_literals())
    stats = t.record(stats, "char_literals", lex_tests.test_char_literals())
    stats = t.record(stats, "string_literal_escapes", lex_tests.test_string_literal_escapes())
    stats = t.record(stats, "cstring_literal", lex_tests.test_cstring_literal())
    stats = t.record(stats, "heredoc_cstring", lex_tests.test_heredoc_cstring())
    stats = t.record(stats, "heredoc_string", lex_tests.test_heredoc_string())
    stats = t.record(stats, "format_string", lex_tests.test_format_string())
    stats = t.record(stats, "operators", lex_tests.test_operators())
    stats = t.record(stats, "assignment_operators", lex_tests.test_assignment_operators())
    stats = t.record(stats, "indentation_increases", lex_tests.test_indentation_increases())
    stats = t.record(stats, "grouping_suppresses_newlines", lex_tests.test_grouping_suppresses_newlines())
    stats = t.record(stats, "line_continuation", lex_tests.test_line_continuation())
    stats = t.record(stats, "comments_are_skipped", lex_tests.test_comments_are_skipped())
    stats = t.record(stats, "comment_only_source", lex_tests.test_comment_only_source())
    stats = t.record(stats, "empty_source", lex_tests.test_empty_source())
    stats = t.record(stats, "adjacent_strings", lex_tests.test_adjacent_strings())
    stats = t.record(stats, "parallel_keyword", lex_tests.test_parallel_keyword())

    stats = t.record(stats, "parses_function", parse_tests.test_parses_function())
    stats = t.record(stats, "parses_const", parse_tests.test_parses_const())
    stats = t.record(stats, "parses_var", parse_tests.test_parses_var())
    stats = t.record(stats, "parses_type_alias", parse_tests.test_parses_type_alias())
    stats = t.record(stats, "parses_struct", parse_tests.test_parses_struct())
    stats = t.record(stats, "parses_enum", parse_tests.test_parses_enum())
    stats = t.record(stats, "parses_flags", parse_tests.test_parses_flags())
    stats = t.record(stats, "parses_union", parse_tests.test_parses_union())
    stats = t.record(stats, "parses_variant", parse_tests.test_parses_variant())
    stats = t.record(stats, "parses_opaque", parse_tests.test_parses_opaque())
    stats = t.record(stats, "parses_interface", parse_tests.test_parses_interface())
    stats = t.record(stats, "parses_extending", parse_tests.test_parses_extending())
    stats = t.record(stats, "parses_public_declaration", parse_tests.test_parses_public_declaration())
    stats = t.record(stats, "parses_generic_struct", parse_tests.test_parses_generic_struct())
    stats = t.record(stats, "parses_generic_function", parse_tests.test_parses_generic_function())
    stats = t.record(stats, "parses_async_function", parse_tests.test_parses_async_function())
    stats = t.record(stats, "parses_const_function", parse_tests.test_parses_const_function())
    stats = t.record(stats, "parses_extern_function", parse_tests.test_parses_extern_function())
    stats = t.record(stats, "parses_foreign_function", parse_tests.test_parses_foreign_function())
    stats = t.record(stats, "parses_ref_param", parse_tests.test_parses_ref_param())
    stats = t.record(stats, "parses_return_type_with_brackets", parse_tests.test_parses_return_type_with_brackets())
    stats = t.record(stats, "parses_inline_if", parse_tests.test_parses_inline_if())
    stats = t.record(stats, "parses_attribute_declaration", parse_tests.test_parses_attribute_declaration())
    stats = t.record(stats, "parses_module_when", parse_tests.test_parses_module_when())
    stats = t.record(stats, "parses_event", parse_tests.test_parses_event())
    stats = t.record(stats, "parses_multiple_declarations", parse_tests.test_parses_multiple_declarations())
    stats = t.record(stats, "parses_empty_file", parse_tests.test_parses_empty_file())
    stats = t.record(stats, "parses_comment_only", parse_tests.test_parses_comment_only())
    stats = t.record(stats, "parses_function_with_many_params", parse_tests.test_parses_function_with_many_params())

    return t.summarize(stats)
