# frozen_string_literal: true

module MilkTea
  module AST
    class QualifiedName < Data.define(:parts)
      def to_s
        parts.join(".")
      end
    end

    TypeParam = Data.define(:name)
    TypeArgument = Data.define(:value)
    TypeRef = Data.define(:name, :arguments, :nullable)
    FunctionType = Data.define(:params, :return_type)
    SourceFile = Data.define(:module_name, :module_kind, :imports, :directives, :declarations)
    Import = Data.define(:path, :alias_name)
    LinkDirective = Data.define(:value)
    IncludeDirective = Data.define(:value)
    ConstDecl = Data.define(:name, :type, :value)
    TypeAliasDecl = Data.define(:name, :target)
    StructDecl = Data.define(:name, :type_params, :fields, :packed, :alignment)
    UnionDecl = Data.define(:name, :fields)
    Field = Data.define(:name, :type)
    EnumDecl = Data.define(:name, :backing_type, :members)
    FlagsDecl = Data.define(:name, :backing_type, :members)
    EnumMember = Data.define(:name, :value)
    OpaqueDecl = Data.define(:name)
    MethodsBlock = Data.define(:type_name, :methods)
    FunctionDef = Data.define(:name, :type_params, :params, :return_type, :body)
    MethodDef = Data.define(:name, :type_params, :params, :return_type, :body, :kind)
    ExternFunctionDecl = Data.define(:name, :type_params, :params, :return_type, :variadic)
    Param = Data.define(:name, :type, :mutable)
    LocalDecl = Data.define(:kind, :name, :type, :value)
    Assignment = Data.define(:target, :operator, :value)
    IfBranch = Data.define(:condition, :body)
    IfStmt = Data.define(:branches, :else_body)
    MatchArm = Data.define(:pattern, :body)
    MatchStmt = Data.define(:expression, :arms)
    UnsafeStmt = Data.define(:body)
    StaticAssert = Data.define(:condition, :message)
    ForStmt = Data.define(:name, :iterable, :body)
    WhileStmt = Data.define(:condition, :body)
    BreakStmt = Data.define()
    ContinueStmt = Data.define()
    ReturnStmt = Data.define(:value)
    DeferStmt = Data.define(:expression)
    ExpressionStmt = Data.define(:expression)

    Identifier = Data.define(:name)
    MemberAccess = Data.define(:receiver, :member)
    PointerMemberAccess = Data.define(:receiver, :member)
    IndexAccess = Data.define(:receiver, :index)
    Specialization = Data.define(:callee, :arguments)
    Call = Data.define(:callee, :arguments)
    Argument = Data.define(:name, :value)
    UnaryOp = Data.define(:operator, :operand)
    BinaryOp = Data.define(:operator, :left, :right)
    SizeofExpr = Data.define(:type)
    AlignofExpr = Data.define(:type)
    OffsetofExpr = Data.define(:type, :field)
    IntegerLiteral = Data.define(:lexeme, :value)
    FloatLiteral = Data.define(:lexeme, :value)
    StringLiteral = Data.define(:lexeme, :value, :cstring)
    BooleanLiteral = Data.define(:value)
    NullLiteral = Data.define()
  end
end
