# frozen_string_literal: true

require_relative "base"
require_relative "core"

require_relative "bindings/bindgen"
require_relative "bindings/raw_bindings"
require_relative "bindings/imported_bindings"
require_relative "bindings/vendored_c_library"
require_relative "bindings/vendored_raylib"
require_relative "bindings/vendored_sdl3"
require_relative "bindings/vendored_glfw"
require_relative "bindings/vendored_box2d"
require_relative "bindings/vendored_cjson"
require_relative "bindings/vendored_flecs"
require_relative "bindings/vendored_libuv"
require_relative "bindings/vendored_pcre2"
require_relative "bindings/steamworks"
require_relative "bindings/vendored_steamworks"
require_relative "bindings/vendored_tracy"
require_relative "bindings/vendored_tools"
require_relative "bindings/upstream_sources"
require_relative "bindings/opengl_registry"
