# frozen_string_literal: true

require_relative "base"

require_relative "core/keywords"
require_relative "core/token"
require_relative "core/token_stream"
require_relative "core/lexer"
require_relative "core/cst"
require_relative "core/cst_builder"
require_relative "core/ast"
require_relative "core/types/types"
require_relative "core/binding_types"
require_relative "core/compile_time"
require_relative "core/compile_time/method_kinds"
require_relative "core/parser"
require_relative "core/module_roots"
require_relative "core/module_loader"
require_relative "core/semantic_analyzer"
require_relative "core/ir"
require_relative "core/cfg"
require_relative "core/pretty_printer"
require_relative "core/lowering"
# Codegen wrapper deleted; use CBackend.emit directly
require_relative "core/c_backend"
require_relative "core/ir_json"
