# frozen_string_literal: true

module MilkTea
  module IR
    Program = Data.define(:module_name, :includes, :constants, :globals, :opaques, :structs, :unions, :enums, :static_asserts, :functions)
    Include = Data.define(:header)
    Constant = Data.define(:name, :c_name, :type, :value)
    Global = Data.define(:name, :c_name, :type, :value)
    OpaqueDecl = Data.define(:name, :c_name, :forward_declarable)
      StructDecl = Data.define(:name, :c_name, :fields, :packed, :alignment)
    UnionDecl = Data.define(:name, :c_name, :fields)
    EnumDecl = Data.define(:name, :c_name, :backing_type, :members, :flags)
    EnumMember = Data.define(:name, :c_name, :value)
    Field = Data.define(:name, :type)
    Function = Data.define(:name, :c_name, :params, :return_type, :body, :entry_point)
    Param = Data.define(:name, :c_name, :type, :pointer)

    LocalDecl = Data.define(:name, :c_name, :type, :value)
    Assignment = Data.define(:target, :operator, :value)
    BlockStmt = Data.define(:body)
    IfStmt = Data.define(:condition, :then_body, :else_body)
    SwitchCase = Data.define(:value, :body)
    SwitchStmt = Data.define(:expression, :cases)
    WhileStmt = Data.define(:condition, :body)
    ForStmt = Data.define(:init, :condition, :post, :body)
    BreakStmt = Data.define()
    ContinueStmt = Data.define()
    GotoStmt = Data.define(:label)
    LabelStmt = Data.define(:name)
    StaticAssert = Data.define(:condition, :message)
    ReturnStmt = Data.define(:value)
    ExpressionStmt = Data.define(:expression)

    Name = Data.define(:name, :type, :pointer)
    Member = Data.define(:receiver, :member, :type)
    Index = Data.define(:receiver, :index, :type)
    CheckedIndex = Data.define(:receiver, :index, :receiver_type, :type)
    CheckedSpanIndex = Data.define(:receiver, :index, :receiver_type, :type)
    Call = Data.define(:callee, :arguments, :type)
    Unary = Data.define(:operator, :operand, :type)
    Binary = Data.define(:operator, :left, :right, :type)
    Conditional = Data.define(:condition, :then_expression, :else_expression, :type)
    ReinterpretExpr = Data.define(:target_type, :source_type, :expression, :type)
    SizeofExpr = Data.define(:target_type, :type)
    AlignofExpr = Data.define(:target_type, :type)
    OffsetofExpr = Data.define(:target_type, :field, :type)
    IntegerLiteral = Data.define(:value, :type)
    FloatLiteral = Data.define(:value, :type)
    StringLiteral = Data.define(:value, :type, :cstring)
    BooleanLiteral = Data.define(:value, :type)
    NullLiteral = Data.define(:type)
    ZeroInit = Data.define(:type)
    AddressOf = Data.define(:expression, :type)
    Cast = Data.define(:target_type, :expression, :type)
    AggregateLiteral = Data.define(:type, :fields)
    AggregateField = Data.define(:name, :value)
    ArrayLiteral = Data.define(:type, :elements)
  end
end
