# frozen_string_literal: true

module MilkTea
  module RawBindings
    class Error < StandardError; end

    class Binding
      attr_reader :name, :module_name, :binding_path, :include_directives, :link_libraries, :link_flags, :header_candidates, :env_var, :clang_args, :compiler_flags, :implementation_defines, :function_param_type_overrides

      def initialize(name:, module_name:, binding_path:, header_candidates:, include_directives: nil, link_libraries: [], link_flags: [], env_var: nil, clang: nil, clang_args: [], compiler_flags: [], implementation_defines: [], function_param_type_overrides: {}, prepare: nil)
        @name = name.to_s
        @module_name = module_name
        @binding_path = File.expand_path(binding_path.to_s)
        @header_candidates = header_candidates.map { |path| File.expand_path(path) }.freeze
        @include_directives = include_directives&.dup&.freeze
        @link_libraries = link_libraries.dup.freeze
        @link_flags = link_flags.dup.freeze
        @env_var = env_var
        @clang = clang
        @clang_args = clang_args.dup.freeze
        @compiler_flags = compiler_flags.dup.freeze
        @implementation_defines = implementation_defines.dup.freeze
        @function_param_type_overrides = normalize_function_param_type_overrides(function_param_type_overrides)
        @prepare = prepare
      end

      def task_name
        "bindgen:#{name}"
      end

      def check_task_name
        "bindgen:check:#{name}"
      end

      def legacy_check_task_name
        "bindgen:check_#{name}"
      end

      def header_label
        return include_directives.first if include_directives && !include_directives.empty?
        return File.basename(header_candidates.first) unless header_candidates.empty?

        name
      end

      def header_path(env: ENV)
        candidates = []
        override = env_var && env[env_var]
        candidates << override unless override.nil? || override.empty?
        candidates.concat(header_candidates)

        resolved = candidates.find { |path| File.file?(path) }
        return resolved if resolved

        if env_var
          raise Error, "#{header_label} header not found; set #{env_var} or install #{header_label} headers"
        end

        raise Error, "#{header_label} header not found"
      end

      def generate(env: ENV, header_path: nil)
        resolved_header_path = header_path || self.header_path(env:)

        MilkTea::Bindgen.generate(
          module_name:,
          header_path: resolved_header_path,
          link_libraries:,
          include_directives:,
          clang: resolved_clang(env),
          clang_args:,
          function_param_type_overrides:,
        )
      end

      def build_flags(env: ENV, header_path: nil)
        resolved_header_path = header_path || self.header_path(env:)
        include_dir = File.dirname(resolved_header_path)
        flags = []
        flags << "-I#{include_dir}" unless include_dir.nil? || include_dir.empty?
        implementation_defines.each do |define|
          flags << "-D#{define}"
        end
        flags.concat(compiler_flags)
        flags.uniq
      end

      def write!(env: ENV)
        resolved_header_path = header_path(env:)
        File.write(binding_path, generate(env:, header_path: resolved_header_path))
        resolved_header_path
      end

      def check!(env: ENV)
        resolved_header_path = header_path(env:)
        expected = normalized_output(File.read(binding_path))
        actual = normalized_output(generate(env:, header_path: resolved_header_path))

        if expected != actual
          raise Error, <<~MESSAGE
            #{binding_path} is out of date for #{resolved_header_path}
            Run `rake #{task_name}` to regenerate it.
          MESSAGE
        end

        MilkTea::ModuleLoader.check_file(binding_path)
        resolved_header_path
      end

      def prepare!(env: ENV, cc: ENV.fetch("CC", "cc"))
        @prepare&.call(self, env:, cc:)
      end

      private

      def normalize_function_param_type_overrides(overrides)
        overrides.each_with_object({}) do |(function_name, param_overrides), normalized|
          normalized[function_name.to_s] = param_overrides.each_with_object({}) do |(param_name, type), params|
            params[param_name.to_s] = type.to_s
          end.freeze
        end.freeze
      end

      def resolved_clang(env)
        @clang || env.fetch("CLANG", "clang")
      end

      def normalized_output(source)
        source.sub(/\A# generated by mtc bindgen from .*\n/, "# generated by mtc bindgen from <header>\n")
      end
    end

    class Registry
      include Enumerable

      def initialize(bindings = [])
        @bindings = {}
        @bindings_by_module_name = {}
        bindings.each { |binding| register(binding) }
      end

      def register(binding)
        raise Error, "duplicate raw binding #{binding.name}" if @bindings.key?(binding.name)
        raise Error, "duplicate raw binding module #{binding.module_name}" if @bindings_by_module_name.key?(binding.module_name)

        @bindings[binding.name] = binding
        @bindings_by_module_name[binding.module_name] = binding
      end

      def fetch(name)
        @bindings.fetch(name.to_s)
      rescue KeyError
        raise Error, "unknown raw binding #{name}"
      end

      def each(&block)
        @bindings.each_value(&block)
      end

      def find_by_module_name(module_name)
        @bindings_by_module_name[module_name]
      end

      def task_names
        map(&:task_name)
      end

      def check_task_names
        map(&:check_task_name)
      end
    end

    def self.default_bindings(root: MilkTea.root)
      font_codepoint_param_overrides = {
        "LoadFontEx" => { "codepoints" => "ptr[i32]?" },
        "LoadFontFromMemory" => { "codepoints" => "ptr[i32]?" },
        "LoadFontData" => { "codepoints" => "ptr[i32]?" },
      }.freeze

      [
        Binding.new(
          name: "raylib",
          module_name: "std.c.raylib",
          binding_path: root.join("std/c/raylib.mt"),
          include_directives: ["raylib.h"],
          link_libraries: ["raylib"],
          link_flags: MilkTea::VendoredRaylib.link_flags,
          env_var: "RAYLIB_HEADER",
          header_candidates: [
            root.join("third_party/raylib-upstream/src/raylib.h").to_s,
            "/usr/include/raylib.h",
            "/usr/local/include/raylib.h",
          ],
          function_param_type_overrides: font_codepoint_param_overrides,
          prepare: ->(_binding, env:, cc:) do
            MilkTea::VendoredRaylib.prepare!(cc: env.fetch("RAYLIB_CC", ENV.fetch("CC", "cc")))
          end,
        ),
        Binding.new(
          name: "raygui",
          module_name: "std.c.raygui",
          binding_path: root.join("std/c/raygui.mt"),
          include_directives: ["raygui.h"],
          link_libraries: ["raylib", "m"],
          env_var: "RAYGUI_HEADER",
          implementation_defines: ["RAYGUI_IMPLEMENTATION"],
          header_candidates: [
            root.join("third_party/raylib-upstream/examples/shapes/raygui.h").to_s,
            "/usr/include/raygui.h",
            "/usr/local/include/raygui.h",
          ],
          function_param_type_overrides: font_codepoint_param_overrides,
        ),
        Binding.new(
          name: "rlgl",
          module_name: "std.c.rlgl",
          binding_path: root.join("std/c/rlgl.mt"),
          include_directives: ["rlgl.h"],
          link_libraries: ["raylib"],
          env_var: "RLGL_HEADER",
          header_candidates: [
            "/usr/include/rlgl.h",
            "/usr/local/include/rlgl.h",
            root.join("third_party/raylib-upstream/src/rlgl.h").to_s,
          ],
        ),
        Binding.new(
          name: "msf_gif",
          module_name: "std.c.msf_gif",
          binding_path: root.join("std/c/msf_gif.mt"),
          include_directives: ["msf_gif.h"],
          implementation_defines: ["MSF_GIF_IMPL"],
          header_candidates: [
            root.join("third_party/raylib-upstream/examples/core/msf_gif.h").to_s,
          ],
        ),
        Binding.new(
          name: "libc",
          module_name: "std.c.libc",
          binding_path: root.join("std/c/libc.mt"),
          include_directives: ["stdlib.h"],
          env_var: "LIBC_HEADER",
          header_candidates: [
            "/usr/include/stdlib.h",
            "/usr/local/include/stdlib.h",
          ],
        ),
      ]
    end

    def self.default_registry(root: MilkTea.root)
      Registry.new(default_bindings(root:))
    end
  end
end
