import mtc.lexer.token_kinds as tk

public struct Token:
    kind: tk.TokenKind
    start_offset: ptr_uint
    end_offset: ptr_uint
    line: ptr_uint
    column: ptr_uint


public struct LexDiagnostic:
    message: cstr
    line: ptr_uint
    column: ptr_uint


## Extract the source text of a token from the original source string.
## This reconstructs the lexeme from byte offsets — the token does not
## own its lexeme; the caller must ensure `source` is still alive.
public function token_lexeme(token: Token, source: str) -> str:
    return unsafe: str(data = source.data + token.start_offset, len = token.end_offset - token.start_offset)


## Token kind name for debug display.  Returns a human-readable string
## matching the Ruby lexer's Symbol names (e.g. `:identifier`, `:string`,
## `:eof`).  Unknown kinds return `"unknown"`.
public function kind_name(kind: tk.TokenKind) -> str:
    return match kind:
        tk.TokenKind.eof:               "eof"
        tk.TokenKind.newline:           "newline"
        tk.TokenKind.indent:            "indent"
        tk.TokenKind.dedent:            "dedent"
        tk.TokenKind.identifier:        "identifier"
        tk.TokenKind.integer:           "integer"
        tk.TokenKind.float_literal:     "float"
        tk.TokenKind.string:            "string"
        tk.TokenKind.cstring:           "cstring"
        tk.TokenKind.char_literal:      "char_literal"
        tk.TokenKind.fstring:           "fstring"
        tk.TokenKind.dot:               "dot"
        tk.TokenKind.colon:             "colon"
        tk.TokenKind.comma:             "comma"
        tk.TokenKind.question:          "question"
        tk.TokenKind.at:                "at"
        tk.TokenKind.tilde:             "tilde"
        tk.TokenKind.lparen:            "lparen"
        tk.TokenKind.rparen:            "rparen"
        tk.TokenKind.lbracket:          "lbracket"
        tk.TokenKind.rbracket:          "rbracket"
        tk.TokenKind.plus:              "plus"
        tk.TokenKind.minus:             "minus"
        tk.TokenKind.star:              "star"
        tk.TokenKind.slash:             "slash"
        tk.TokenKind.percent:           "percent"
        tk.TokenKind.amp:               "amp"
        tk.TokenKind.pipe:              "pipe"
        tk.TokenKind.caret:             "caret"
        tk.TokenKind.less:              "less"
        tk.TokenKind.greater:           "greater"
        tk.TokenKind.equal:             "equal"
        tk.TokenKind.arrow:             "arrow"
        tk.TokenKind.dot_dot:           "dot_dot"
        tk.TokenKind.equal_equal:       "equal_equal"
        tk.TokenKind.bang_equal:        "bang_equal"
        tk.TokenKind.less_equal:        "less_equal"
        tk.TokenKind.greater_equal:     "greater_equal"
        tk.TokenKind.shift_left:        "shift_left"
        tk.TokenKind.shift_right:       "shift_right"
        tk.TokenKind.plus_equal:        "plus_equal"
        tk.TokenKind.minus_equal:       "minus_equal"
        tk.TokenKind.star_equal:        "star_equal"
        tk.TokenKind.slash_equal:       "slash_equal"
        tk.TokenKind.percent_equal:     "percent_equal"
        tk.TokenKind.amp_equal:         "amp_equal"
        tk.TokenKind.pipe_equal:        "pipe_equal"
        tk.TokenKind.caret_equal:       "caret_equal"
        tk.TokenKind.shift_left_equal:  "shift_left_equal"
        tk.TokenKind.shift_right_equal: "shift_right_equal"
        tk.TokenKind.ellipsis:          "ellipsis"
        tk.TokenKind.tk_align_of:       "align_of"
        tk.TokenKind.tk_and:            "and"
        tk.TokenKind.tk_as:             "as"
        tk.TokenKind.tk_async:          "async"
        tk.TokenKind.tk_attribute:      "attribute"
        tk.TokenKind.tk_attribute_arg:  "attribute_arg"
        tk.TokenKind.tk_attribute_of:   "attribute_of"
        tk.TokenKind.tk_attributes_of:  "attributes_of"
        tk.TokenKind.tk_await:          "await"
        tk.TokenKind.tk_break:          "break"
        tk.TokenKind.tk_callable_of:    "callable_of"
        tk.TokenKind.tk_compiler_flag:  "compiler_flag"
        tk.TokenKind.tk_const:          "const"
        tk.TokenKind.tk_consuming:      "consuming"
        tk.TokenKind.tk_continue:       "continue"
        tk.TokenKind.tk_defer:          "defer"
        tk.TokenKind.tk_detach:         "detach"
        tk.TokenKind.tk_dyn:            "dyn"
        tk.TokenKind.tk_editable:       "editable"
        tk.TokenKind.tk_else:           "else"
        tk.TokenKind.tk_emit:           "emit"
        tk.TokenKind.tk_enum:           "enum"
        tk.TokenKind.tk_event:          "event"
        tk.TokenKind.tk_extending:      "extending"
        tk.TokenKind.tk_external:       "external"
        tk.TokenKind.tk_false:          "false"
        tk.TokenKind.tk_field_of:       "field_of"
        tk.TokenKind.tk_fields_of:      "fields_of"
        tk.TokenKind.tk_flags:          "flags"
        tk.TokenKind.tk_fn:             "fn"
        tk.TokenKind.tk_for:            "for"
        tk.TokenKind.tk_foreign:        "foreign"
        tk.TokenKind.tk_function:       "function"
        tk.TokenKind.tk_gather:         "gather"
        tk.TokenKind.tk_has_attribute:  "has_attribute"
        tk.TokenKind.tk_if:             "if"
        tk.TokenKind.tk_implements:     "implements"
        tk.TokenKind.tk_import:         "import"
        tk.TokenKind.tk_in:             "in"
        tk.TokenKind.tk_include:        "include"
        tk.TokenKind.tk_inline:         "inline"
        tk.TokenKind.tk_inout:          "inout"
        tk.TokenKind.tk_interface:      "interface"
        tk.TokenKind.tk_is:             "is"
        tk.TokenKind.tk_let:            "let"
        tk.TokenKind.tk_link:           "link"
        tk.TokenKind.tk_match:          "match"
        tk.TokenKind.tk_members_of:     "members_of"
        tk.TokenKind.tk_module:         "module"
        tk.TokenKind.tk_not:            "not"
        tk.TokenKind.tk_null:           "null"
        tk.TokenKind.tk_offset_of:      "offset_of"
        tk.TokenKind.tk_opaque:         "opaque"
        tk.TokenKind.tk_or:             "or"
        tk.TokenKind.tk_out:            "out"
        tk.TokenKind.tk_parallel:       "parallel"
        tk.TokenKind.tk_pass:           "pass"
        tk.TokenKind.tk_proc:           "proc"
        tk.TokenKind.tk_public:         "public"
        tk.TokenKind.tk_return:         "return"
        tk.TokenKind.tk_size_of:        "size_of"
        tk.TokenKind.tk_static:         "static"
        tk.TokenKind.tk_static_assert:  "static_assert"
        tk.TokenKind.tk_struct:         "struct"
        tk.TokenKind.tk_true:           "true"
        tk.TokenKind.tk_type:           "type"
        tk.TokenKind.tk_union:          "union"
        tk.TokenKind.tk_unsafe:         "unsafe"
        tk.TokenKind.tk_var:            "var"
        tk.TokenKind.tk_variant:        "variant"
        tk.TokenKind.tk_when:           "when"
        tk.TokenKind.tk_while:          "while"
        _:                              "unknown"
