import std.raylib as rl
import std.raylib.runtime as rl_runtime

const SCREEN_WIDTH: int = 800
const SCREEN_HEIGHT: int = 450
const CHECKED_WIDTH: int = 960
const CHECKED_HEIGHT: int = 480
const CHECKED_PIXEL_COUNT: int = CHECKED_WIDTH * CHECKED_HEIGHT


function main() -> int:
    rl.init_window(SCREEN_WIDTH, SCREEN_HEIGHT, "raylib [textures] example - raw data")
    defer rl.close_window()

    if not rl_runtime.enter_asset_directory("../resources"):
        fatal("could not enter examples/raylib/resources")

    let fudesumi_raw = rl.load_image_raw(
        "fudesumi.raw",
        384,
        512,
        int<-rl.PixelFormat.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8,
        0
    )
    let fudesumi = rl.load_texture_from_image(fudesumi_raw)
    defer rl.unload_texture(fudesumi)
    rl.unload_image(fudesumi_raw)

    var checked_pixels: array[rl.Color, CHECKED_PIXEL_COUNT] = zero[array[rl.Color, CHECKED_PIXEL_COUNT]]

    var y = 0
    while y < CHECKED_HEIGHT:
        var x = 0
        while x < CHECKED_WIDTH:
            let pixel_index = (y * CHECKED_WIDTH) + x
            if (((x / 32) + (y / 32)) % 2) == 0:
                checked_pixels[pixel_index] = rl.ORANGE
            else:
                checked_pixels[pixel_index] = rl.GOLD
            x += 1
        y += 1

    let checked_image = rl.Image(
        data = unsafe: ptr[void]<-ptr_of(checked_pixels[0]),
        width = CHECKED_WIDTH,
        height = CHECKED_HEIGHT,
        mipmaps = 1,
        format = int<-rl.PixelFormat.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8
    )

    let checked = rl.load_texture_from_image(checked_image)
    defer rl.unload_texture(checked)

    rl.set_target_fps(60)

    while not rl.window_should_close():
        rl.begin_drawing()
        rl.clear_background(rl.RAYWHITE)

        rl.draw_texture(
            checked,
            SCREEN_WIDTH / 2 - checked.width / 2,
            SCREEN_HEIGHT / 2 - checked.height / 2,
            rl.fade(rl.WHITE, 0.5)
        )
        rl.draw_texture(fudesumi, 430, -30, rl.WHITE)

        rl.draw_text("CHECKED TEXTURE ", 84, 85, 30, rl.BROWN)
        rl.draw_text("GENERATED by CODE", 72, 148, 30, rl.BROWN)
        rl.draw_text("and RAW IMAGE LOADING", 46, 210, 30, rl.BROWN)
        rl.draw_text("(c) Fudesumi sprite by Eiden Marsal", 310, SCREEN_HEIGHT - 20, 10, rl.BROWN)

        rl.end_drawing()

    return 0
