module examples.raylib.textures.textures_raw_data

import std.c.raylib as rl

const raw_width: i32 = 384
const raw_height: i32 = 512
const checked_width: i32 = 960
const checked_height: i32 = 480
const check_size: i32 = 32
const screen_width: i32 = 800
const screen_height: i32 = 450
const window_title: cstr = c"raylib [textures] example - raw data"
const raw_image_path: cstr = c"../resources/fudesumi.raw"
const title_line_one: cstr = c"CHECKED TEXTURE "
const title_line_two: cstr = c"GENERATED by CODE"
const title_line_three: cstr = c"and RAW IMAGE LOADING"
const credit_text: cstr = c"(c) Fudesumi sprite by Eiden Marsal"

def main() -> i32:
    rl.InitWindow(screen_width, screen_height, window_title)
    defer rl.CloseWindow()

    let fudesumi_raw = rl.LoadImageRaw(raw_image_path, raw_width, raw_height, rl.PixelFormat.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 0)
    let fudesumi = rl.LoadTextureFromImage(fudesumi_raw)
    rl.UnloadImage(fudesumi_raw)

    var checked = zero[rl.Texture2D]()
    unsafe:
        let pixel_count = cast[u32](checked_width * checked_height)
        let allocation_size = pixel_count * cast[u32](sizeof(rl.Color))
        let pixels = cast[ptr[rl.Color]](rl.MemAlloc(allocation_size))

        for pos_y in range(0, checked_height):
            for pos_x in range(0, checked_width):
                let pixel_index = pos_y * checked_width + pos_x
                let color = if ((pos_x / check_size) + (pos_y / check_size)) % 2 == 0 then rl.ORANGE else rl.GOLD
                deref(pixels + pixel_index) = color

        let checked_image = rl.Image(
            data = cast[ptr[void]](pixels),
            width = checked_width,
            height = checked_height,
            mipmaps = 1,
            format = rl.PixelFormat.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8,
        )

        checked = rl.LoadTextureFromImage(checked_image)
        rl.UnloadImage(checked_image)

    defer:
        rl.UnloadTexture(checked)
        rl.UnloadTexture(fudesumi)

    rl.SetTargetFPS(60)

    while not rl.WindowShouldClose():
        rl.BeginDrawing()

        rl.ClearBackground(rl.RAYWHITE)
        rl.DrawTexture(checked, screen_width / 2 - checked.width / 2, screen_height / 2 - checked.height / 2, rl.Fade(rl.WHITE, 0.5))
        rl.DrawTexture(fudesumi, 430, -30, rl.WHITE)

        rl.DrawText(title_line_one, 84, 85, 30, rl.BROWN)
        rl.DrawText(title_line_two, 72, 148, 30, rl.BROWN)
        rl.DrawText(title_line_three, 46, 210, 30, rl.BROWN)
        rl.DrawText(credit_text, 310, screen_height - 20, 10, rl.BROWN)

        rl.EndDrawing()

    return 0
