#!/bin/sh
output=''
previous=''
for argument in "$@"; do
  if [ "$previous" = '-o' ]; then
    output="$argument"
  fi
  previous="$argument"
done
cat > "$output" <<'SCRIPT'
#!/bin/sh
printf 'run-ok\n'
printf 'run-err\n' >&2
exit 3
SCRIPT
chmod +x "$output"
