# generated by mtc bindgen from /usr/include/enet/enet.h
external

link "enet"
include "enet/enet.h"
opaque fd_set = c"struct fd_set"
type ENetSocket = int
struct ENetBuffer:
    data: ptr[void]
    dataLength: ptr_uint
type ENetSocketSet = fd_set
type enet_uint8 = ubyte
type enet_uint16 = ushort
type enet_uint32 = uint
enum ENetProtocolCommand: int
    ENET_PROTOCOL_COMMAND_NONE = 0
    ENET_PROTOCOL_COMMAND_ACKNOWLEDGE = 1
    ENET_PROTOCOL_COMMAND_CONNECT = 2
    ENET_PROTOCOL_COMMAND_VERIFY_CONNECT = 3
    ENET_PROTOCOL_COMMAND_DISCONNECT = 4
    ENET_PROTOCOL_COMMAND_PING = 5
    ENET_PROTOCOL_COMMAND_SEND_RELIABLE = 6
    ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE = 7
    ENET_PROTOCOL_COMMAND_SEND_FRAGMENT = 8
    ENET_PROTOCOL_COMMAND_SEND_UNSEQUENCED = 9
    ENET_PROTOCOL_COMMAND_BANDWIDTH_LIMIT = 10
    ENET_PROTOCOL_COMMAND_THROTTLE_CONFIGURE = 11
    ENET_PROTOCOL_COMMAND_SEND_UNRELIABLE_FRAGMENT = 12
    ENET_PROTOCOL_COMMAND_COUNT = 13
    ENET_PROTOCOL_COMMAND_MASK = 15
enum ENetProtocolFlag: int
    ENET_PROTOCOL_COMMAND_FLAG_ACKNOWLEDGE = 128
    ENET_PROTOCOL_COMMAND_FLAG_UNSEQUENCED = 64
    ENET_PROTOCOL_HEADER_FLAG_COMPRESSED = 16384
    ENET_PROTOCOL_HEADER_FLAG_SENT_TIME = 32768
    ENET_PROTOCOL_HEADER_FLAG_MASK = 49152
    ENET_PROTOCOL_HEADER_SESSION_MASK = 12288
    ENET_PROTOCOL_HEADER_SESSION_SHIFT = 12
struct ENetProtocolHeader:
    peerID: ushort
    sentTime: ushort
struct ENetProtocolCommandHeader:
    command: ubyte
    channelID: ubyte
    reliableSequenceNumber: ushort
struct ENetProtocolAcknowledge:
    header: ENetProtocolCommandHeader
    receivedReliableSequenceNumber: ushort
    receivedSentTime: ushort
struct ENetProtocolConnect:
    header: ENetProtocolCommandHeader
    outgoingPeerID: ushort
    incomingSessionID: ubyte
    outgoingSessionID: ubyte
    mtu: uint
    windowSize: uint
    channelCount: uint
    incomingBandwidth: uint
    outgoingBandwidth: uint
    packetThrottleInterval: uint
    packetThrottleAcceleration: uint
    packetThrottleDeceleration: uint
    connectID: uint
    data: uint
struct ENetProtocolVerifyConnect:
    header: ENetProtocolCommandHeader
    outgoingPeerID: ushort
    incomingSessionID: ubyte
    outgoingSessionID: ubyte
    mtu: uint
    windowSize: uint
    channelCount: uint
    incomingBandwidth: uint
    outgoingBandwidth: uint
    packetThrottleInterval: uint
    packetThrottleAcceleration: uint
    packetThrottleDeceleration: uint
    connectID: uint
struct ENetProtocolBandwidthLimit:
    header: ENetProtocolCommandHeader
    incomingBandwidth: uint
    outgoingBandwidth: uint
struct ENetProtocolThrottleConfigure:
    header: ENetProtocolCommandHeader
    packetThrottleInterval: uint
    packetThrottleAcceleration: uint
    packetThrottleDeceleration: uint
struct ENetProtocolDisconnect:
    header: ENetProtocolCommandHeader
    data: uint
struct ENetProtocolPing:
    header: ENetProtocolCommandHeader
struct ENetProtocolSendReliable:
    header: ENetProtocolCommandHeader
    dataLength: ushort
struct ENetProtocolSendUnreliable:
    header: ENetProtocolCommandHeader
    unreliableSequenceNumber: ushort
    dataLength: ushort
struct ENetProtocolSendUnsequenced:
    header: ENetProtocolCommandHeader
    unsequencedGroup: ushort
    dataLength: ushort
struct ENetProtocolSendFragment:
    header: ENetProtocolCommandHeader
    startSequenceNumber: ushort
    dataLength: ushort
    fragmentCount: uint
    fragmentNumber: uint
    totalLength: uint
    fragmentOffset: uint
union ENetProtocol:
    header: ENetProtocolCommandHeader
    acknowledge: ENetProtocolAcknowledge
    connect: ENetProtocolConnect
    verifyConnect: ENetProtocolVerifyConnect
    disconnect: ENetProtocolDisconnect
    ping: ENetProtocolPing
    sendReliable: ENetProtocolSendReliable
    sendUnreliable: ENetProtocolSendUnreliable
    sendUnsequenced: ENetProtocolSendUnsequenced
    sendFragment: ENetProtocolSendFragment
    bandwidthLimit: ENetProtocolBandwidthLimit
    throttleConfigure: ENetProtocolThrottleConfigure
struct ENetListNode:
    next: ptr[ENetListNode]
    previous: ptr[ENetListNode]
type ENetListIterator = ptr[ENetListNode]
struct ENetList:
    sentinel: ENetListNode
external function enet_list_clear(arg0: ptr[ENetList]) -> void
external function enet_list_insert(arg0: ptr[ENetListNode], arg1: ptr[void]) -> ENetListIterator
external function enet_list_remove(arg0: ptr[ENetListNode]) -> ptr[void]
external function enet_list_move(arg0: ptr[ENetListNode], arg1: ptr[void], arg2: ptr[void]) -> ENetListIterator
external function enet_list_size(arg0: ptr[ENetList]) -> ptr_uint
struct ENetCallbacks:
    malloc: fn(arg0: ptr_uint) -> ptr[void]
    free: fn(arg0: ptr[void]) -> void
    no_memory: fn() -> void
external function enet_malloc(arg0: ptr_uint) -> ptr[void]
external function enet_free(arg0: ptr[void]) -> void
type ENetVersion = uint
opaque _ENetHost = c"ENetHost"
opaque _ENetEvent = c"ENetEvent"
opaque _ENetPacket = c"ENetPacket"
flags ENetSocketType: int
    ENET_SOCKET_TYPE_STREAM = 1
    ENET_SOCKET_TYPE_DATAGRAM = 2
flags ENetSocketWait: int
    ENET_SOCKET_WAIT_NONE = 0
    ENET_SOCKET_WAIT_SEND = 1
    ENET_SOCKET_WAIT_RECEIVE = 2
    ENET_SOCKET_WAIT_INTERRUPT = 4
enum ENetSocketOption: int
    ENET_SOCKOPT_NONBLOCK = 1
    ENET_SOCKOPT_BROADCAST = 2
    ENET_SOCKOPT_RCVBUF = 3
    ENET_SOCKOPT_SNDBUF = 4
    ENET_SOCKOPT_REUSEADDR = 5
    ENET_SOCKOPT_RCVTIMEO = 6
    ENET_SOCKOPT_SNDTIMEO = 7
    ENET_SOCKOPT_ERROR = 8
    ENET_SOCKOPT_NODELAY = 9
    ENET_SOCKOPT_TTL = 10
flags ENetSocketShutdown: int
    ENET_SOCKET_SHUTDOWN_READ = 0
    ENET_SOCKET_SHUTDOWN_WRITE = 1
    ENET_SOCKET_SHUTDOWN_READ_WRITE = 2
struct ENetAddress:
    host: uint
    port: ushort
flags ENetPacketFlag: int
    ENET_PACKET_FLAG_RELIABLE = 1
    ENET_PACKET_FLAG_UNSEQUENCED = 2
    ENET_PACKET_FLAG_NO_ALLOCATE = 4
    ENET_PACKET_FLAG_UNRELIABLE_FRAGMENT = 8
    ENET_PACKET_FLAG_SENT = 256
type ENetPacketFreeCallback = fn(arg0: ptr[ENetPacket]) -> void
struct ENetPacket:
    referenceCount: ptr_uint
    flags_: uint
    data: ptr[enet_uint8]
    dataLength: ptr_uint
    freeCallback: fn(arg0: ptr[ENetPacket]) -> void
    userData: ptr[void]
struct ENetAcknowledgement:
    acknowledgementList: ENetListNode
    sentTime: uint
    command: ENetProtocol
struct ENetOutgoingCommand:
    outgoingCommandList: ENetListNode
    reliableSequenceNumber: ushort
    unreliableSequenceNumber: ushort
    sentTime: uint
    roundTripTimeout: uint
    queueTime: uint
    fragmentOffset: uint
    fragmentLength: ushort
    sendAttempts: ushort
    command: ENetProtocol
    packet: ptr[ENetPacket]
struct ENetIncomingCommand:
    incomingCommandList: ENetListNode
    reliableSequenceNumber: ushort
    unreliableSequenceNumber: ushort
    command: ENetProtocol
    fragmentCount: uint
    fragmentsRemaining: uint
    fragments: ptr[enet_uint32]
    packet: ptr[ENetPacket]
enum ENetPeerState: int
    ENET_PEER_STATE_DISCONNECTED = 0
    ENET_PEER_STATE_CONNECTING = 1
    ENET_PEER_STATE_ACKNOWLEDGING_CONNECT = 2
    ENET_PEER_STATE_CONNECTION_PENDING = 3
    ENET_PEER_STATE_CONNECTION_SUCCEEDED = 4
    ENET_PEER_STATE_CONNECTED = 5
    ENET_PEER_STATE_DISCONNECT_LATER = 6
    ENET_PEER_STATE_DISCONNECTING = 7
    ENET_PEER_STATE_ACKNOWLEDGING_DISCONNECT = 8
    ENET_PEER_STATE_ZOMBIE = 9
struct ENetChannel:
    outgoingReliableSequenceNumber: ushort
    outgoingUnreliableSequenceNumber: ushort
    usedReliableWindows: ushort
    reliableWindows: array[enet_uint16, 16]
    incomingReliableSequenceNumber: ushort
    incomingUnreliableSequenceNumber: ushort
    incomingReliableCommands: ENetList
    incomingUnreliableCommands: ENetList
flags ENetPeerFlag: int
    ENET_PEER_FLAG_NEEDS_DISPATCH = 1
    ENET_PEER_FLAG_CONTINUE_SENDING = 2
struct ENetPeer:
    dispatchList: ENetListNode
    host: ptr[ENetHost]
    outgoingPeerID: ushort
    incomingPeerID: ushort
    connectID: uint
    outgoingSessionID: ubyte
    incomingSessionID: ubyte
    address: ENetAddress
    data: ptr[void]
    state: ENetPeerState
    channels: ptr[ENetChannel]
    channelCount: ptr_uint
    incomingBandwidth: uint
    outgoingBandwidth: uint
    incomingBandwidthThrottleEpoch: uint
    outgoingBandwidthThrottleEpoch: uint
    incomingDataTotal: uint
    outgoingDataTotal: uint
    lastSendTime: uint
    lastReceiveTime: uint
    nextTimeout: uint
    earliestTimeout: uint
    packetLossEpoch: uint
    packetsSent: uint
    packetsLost: uint
    packetLoss: uint
    packetLossVariance: uint
    packetThrottle: uint
    packetThrottleLimit: uint
    packetThrottleCounter: uint
    packetThrottleEpoch: uint
    packetThrottleAcceleration: uint
    packetThrottleDeceleration: uint
    packetThrottleInterval: uint
    pingInterval: uint
    timeoutLimit: uint
    timeoutMinimum: uint
    timeoutMaximum: uint
    lastRoundTripTime: uint
    lowestRoundTripTime: uint
    lastRoundTripTimeVariance: uint
    highestRoundTripTimeVariance: uint
    roundTripTime: uint
    roundTripTimeVariance: uint
    mtu: uint
    windowSize: uint
    reliableDataInTransit: uint
    outgoingReliableSequenceNumber: ushort
    acknowledgements: ENetList
    sentReliableCommands: ENetList
    outgoingSendReliableCommands: ENetList
    outgoingCommands: ENetList
    dispatchedCommands: ENetList
    flags_: ushort
    reserved: ushort
    incomingUnsequencedGroup: ushort
    outgoingUnsequencedGroup: ushort
    unsequencedWindow: array[enet_uint32, 32]
    eventData: uint
    totalWaitingData: ptr_uint
struct ENetCompressor:
    context: ptr[void]
    compress: fn(arg0: ptr[void], arg1: const_ptr[ENetBuffer], arg2: ptr_uint, arg3: ptr_uint, arg4: ptr[enet_uint8], arg5: ptr_uint) -> ptr_uint
    decompress: fn(arg0: ptr[void], arg1: const_ptr[enet_uint8], arg2: ptr_uint, arg3: ptr[enet_uint8], arg4: ptr_uint) -> ptr_uint
    destroy: fn(arg0: ptr[void]) -> void
type ENetChecksumCallback = fn(arg0: const_ptr[ENetBuffer], arg1: ptr_uint) -> enet_uint32
type ENetInterceptCallback = fn(arg0: ptr[ENetHost], arg1: ptr[ENetEvent]) -> int
struct ENetHost:
    socket: int
    address: ENetAddress
    incomingBandwidth: uint
    outgoingBandwidth: uint
    bandwidthThrottleEpoch: uint
    mtu: uint
    randomSeed: uint
    recalculateBandwidthLimits: int
    peers: ptr[ENetPeer]
    peerCount: ptr_uint
    channelLimit: ptr_uint
    serviceTime: uint
    dispatchQueue: ENetList
    totalQueued: uint
    packetSize: ptr_uint
    headerFlags: ushort
    commands: array[ENetProtocol, 32]
    commandCount: ptr_uint
    buffers: array[ENetBuffer, 65]
    bufferCount: ptr_uint
    checksum: fn(arg0: const_ptr[ENetBuffer], arg1: ptr_uint) -> enet_uint32
    compressor: ENetCompressor
    packetData: array[array[enet_uint8, 2], 4096]
    receivedAddress: ENetAddress
    receivedData: ptr[enet_uint8]
    receivedDataLength: ptr_uint
    totalSentData: uint
    totalSentPackets: uint
    totalReceivedData: uint
    totalReceivedPackets: uint
    intercept: fn(arg0: ptr[ENetHost], arg1: ptr[ENetEvent]) -> int
    connectedPeers: ptr_uint
    bandwidthLimitedPeers: ptr_uint
    duplicatePeers: ptr_uint
    maximumPacketSize: ptr_uint
    maximumWaitingData: ptr_uint
enum ENetEventType: int
    ENET_EVENT_TYPE_NONE = 0
    ENET_EVENT_TYPE_CONNECT = 1
    ENET_EVENT_TYPE_DISCONNECT = 2
    ENET_EVENT_TYPE_RECEIVE = 3
struct ENetEvent:
    type_: ENetEventType
    peer: ptr[ENetPeer]
    channelID: ubyte
    data: uint
    packet: ptr[ENetPacket]
external function enet_initialize() -> int
external function enet_initialize_with_callbacks(version: uint, inits: const_ptr[ENetCallbacks]) -> int
external function enet_deinitialize() -> void
external function enet_linked_version() -> ENetVersion
external function enet_time_get() -> enet_uint32
external function enet_time_set(arg0: uint) -> void
external function enet_socket_create(arg0: ENetSocketType) -> ENetSocket
external function enet_socket_bind(arg0: int, arg1: const_ptr[ENetAddress]) -> int
external function enet_socket_get_address(arg0: int, arg1: ptr[ENetAddress]) -> int
external function enet_socket_listen(arg0: int, arg1: int) -> int
external function enet_socket_accept(arg0: int, arg1: ptr[ENetAddress]) -> ENetSocket
external function enet_socket_connect(arg0: int, arg1: const_ptr[ENetAddress]) -> int
external function enet_socket_send(arg0: int, arg1: const_ptr[ENetAddress], arg2: const_ptr[ENetBuffer], arg3: ptr_uint) -> int
external function enet_socket_receive(arg0: int, arg1: ptr[ENetAddress], arg2: ptr[ENetBuffer], arg3: ptr_uint) -> int
external function enet_socket_wait(arg0: int, arg1: ptr[enet_uint32], arg2: uint) -> int
external function enet_socket_set_option(arg0: int, arg1: ENetSocketOption, arg2: int) -> int
external function enet_socket_get_option(arg0: int, arg1: ENetSocketOption, arg2: ptr[int]) -> int
external function enet_socket_shutdown(arg0: int, arg1: ENetSocketShutdown) -> int
external function enet_socket_destroy(arg0: int) -> void
external function enet_socketset_select(arg0: int, arg1: ptr[ENetSocketSet], arg2: ptr[ENetSocketSet], arg3: uint) -> int
external function enet_address_set_host_ip(address: ptr[ENetAddress], hostName: cstr) -> int
external function enet_address_set_host(address: ptr[ENetAddress], hostName: cstr) -> int
external function enet_address_get_host_ip(address: const_ptr[ENetAddress], hostName: ptr[char], nameLength: ptr_uint) -> int
external function enet_address_get_host(address: const_ptr[ENetAddress], hostName: ptr[char], nameLength: ptr_uint) -> int
external function enet_packet_create(arg0: const_ptr[void], arg1: ptr_uint, arg2: uint) -> ptr[ENetPacket]
external function enet_packet_destroy(arg0: ptr[ENetPacket]) -> void
external function enet_packet_resize(arg0: ptr[ENetPacket], arg1: ptr_uint) -> int
external function enet_crc32(arg0: const_ptr[ENetBuffer], arg1: ptr_uint) -> enet_uint32
external function enet_host_create(arg0: const_ptr[ENetAddress], arg1: ptr_uint, arg2: ptr_uint, arg3: uint, arg4: uint) -> ptr[ENetHost]
external function enet_host_destroy(arg0: ptr[ENetHost]) -> void
external function enet_host_connect(arg0: ptr[ENetHost], arg1: const_ptr[ENetAddress], arg2: ptr_uint, arg3: uint) -> ptr[ENetPeer]
external function enet_host_check_events(arg0: ptr[ENetHost], arg1: ptr[ENetEvent]) -> int
external function enet_host_service(arg0: ptr[ENetHost], arg1: ptr[ENetEvent], arg2: uint) -> int
external function enet_host_flush(arg0: ptr[ENetHost]) -> void
external function enet_host_broadcast(arg0: ptr[ENetHost], arg1: ubyte, arg2: ptr[ENetPacket]) -> void
external function enet_host_compress(arg0: ptr[ENetHost], arg1: const_ptr[ENetCompressor]) -> void
external function enet_host_compress_with_range_coder(host: ptr[ENetHost]) -> int
external function enet_host_channel_limit(arg0: ptr[ENetHost], arg1: ptr_uint) -> void
external function enet_host_bandwidth_limit(arg0: ptr[ENetHost], arg1: uint, arg2: uint) -> void
external function enet_host_bandwidth_throttle(arg0: ptr[ENetHost]) -> void
external function enet_host_random_seed() -> enet_uint32
external function enet_host_random(arg0: ptr[ENetHost]) -> enet_uint32
external function enet_peer_send(arg0: ptr[ENetPeer], arg1: ubyte, arg2: ptr[ENetPacket]) -> int
external function enet_peer_receive(arg0: ptr[ENetPeer], channelID: ptr[enet_uint8]) -> ptr[ENetPacket]
external function enet_peer_ping(arg0: ptr[ENetPeer]) -> void
external function enet_peer_ping_interval(arg0: ptr[ENetPeer], arg1: uint) -> void
external function enet_peer_timeout(arg0: ptr[ENetPeer], arg1: uint, arg2: uint, arg3: uint) -> void
external function enet_peer_reset(arg0: ptr[ENetPeer]) -> void
external function enet_peer_disconnect(arg0: ptr[ENetPeer], arg1: uint) -> void
external function enet_peer_disconnect_now(arg0: ptr[ENetPeer], arg1: uint) -> void
external function enet_peer_disconnect_later(arg0: ptr[ENetPeer], arg1: uint) -> void
external function enet_peer_throttle_configure(arg0: ptr[ENetPeer], arg1: uint, arg2: uint, arg3: uint) -> void
external function enet_peer_throttle(arg0: ptr[ENetPeer], arg1: uint) -> int
external function enet_peer_reset_queues(arg0: ptr[ENetPeer]) -> void
external function enet_peer_has_outgoing_commands(arg0: ptr[ENetPeer]) -> int
external function enet_peer_setup_outgoing_command(arg0: ptr[ENetPeer], arg1: ptr[ENetOutgoingCommand]) -> void
external function enet_peer_queue_outgoing_command(arg0: ptr[ENetPeer], arg1: const_ptr[ENetProtocol], arg2: ptr[ENetPacket], arg3: uint, arg4: ushort) -> ptr[ENetOutgoingCommand]
external function enet_peer_queue_incoming_command(arg0: ptr[ENetPeer], arg1: const_ptr[ENetProtocol], arg2: const_ptr[void], arg3: ptr_uint, arg4: uint, arg5: uint) -> ptr[ENetIncomingCommand]
external function enet_peer_queue_acknowledgement(arg0: ptr[ENetPeer], arg1: const_ptr[ENetProtocol], arg2: ushort) -> ptr[ENetAcknowledgement]
external function enet_peer_dispatch_incoming_unreliable_commands(arg0: ptr[ENetPeer], arg1: ptr[ENetChannel], arg2: ptr[ENetIncomingCommand]) -> void
external function enet_peer_dispatch_incoming_reliable_commands(arg0: ptr[ENetPeer], arg1: ptr[ENetChannel], arg2: ptr[ENetIncomingCommand]) -> void
external function enet_peer_on_connect(arg0: ptr[ENetPeer]) -> void
external function enet_peer_on_disconnect(arg0: ptr[ENetPeer]) -> void
external function enet_range_coder_create() -> ptr[void]
external function enet_range_coder_destroy(arg0: ptr[void]) -> void
external function enet_range_coder_compress(arg0: ptr[void], arg1: const_ptr[ENetBuffer], arg2: ptr_uint, arg3: ptr_uint, arg4: ptr[enet_uint8], arg5: ptr_uint) -> ptr_uint
external function enet_range_coder_decompress(arg0: ptr[void], arg1: const_ptr[enet_uint8], arg2: ptr_uint, arg3: ptr[enet_uint8], arg4: ptr_uint) -> ptr_uint
external function enet_protocol_command_size(arg0: ubyte) -> ptr_uint
const ENET_SOCKET_NULL: int = -1
const ENET_VERSION_MAJOR: int = 1
const ENET_VERSION_MINOR: int = 3
const ENET_VERSION_PATCH: int = 18
const ENET_HOST_ANY: int = 0
const ENET_HOST_BROADCAST: uint = 4294967295
const ENET_PORT_ANY: int = 0
