# generated by mtc bindgen from /usr/include/stdlib.h
external

include "stdlib.h"
opaque __fsid_t = c"struct __fsid_t"
struct div_t:
    quot: int
    rem: int
struct ldiv_t:
    quot: ptr_int
    rem: ptr_int
struct lldiv_t:
    quot: long
    rem: long
external function __ctype_get_mb_cur_max() -> ptr_uint
external function atof(__nptr: cstr) -> double
external function atoi(__nptr: cstr) -> int
external function atol(__nptr: cstr) -> ptr_int
external function atoll(__nptr: cstr) -> long
external function strtod(__nptr: cstr, __endptr: ptr[ptr[char]]?) -> double
external function strtof(__nptr: cstr, __endptr: ptr[ptr[char]]?) -> float
external function strtol(__nptr: cstr, __endptr: ptr[ptr[char]]?, __base: int) -> ptr_int
external function strtoul(__nptr: cstr, __endptr: ptr[ptr[char]]?, __base: int) -> ptr_uint
external function strtoq(__nptr: cstr, __endptr: ptr[ptr[char]]?, __base: int) -> long
external function strtouq(__nptr: cstr, __endptr: ptr[ptr[char]]?, __base: int) -> ulong
external function strtoll(__nptr: cstr, __endptr: ptr[ptr[char]]?, __base: int) -> long
external function strtoull(__nptr: cstr, __endptr: ptr[ptr[char]]?, __base: int) -> ulong
external function l64a(__n: ptr_int) -> ptr[char]
external function a64l(__s: cstr) -> ptr_int
type u_short = ushort
type u_int = uint
type u_long = ptr_uint
type quad_t = ptr_int
type u_quad_t = ptr_uint
type fsid_t = __fsid_t
type loff_t = ptr_int
type ino_t = ptr_uint
type dev_t = ptr_uint
type gid_t = uint
type mode_t = uint
type nlink_t = ptr_uint
type uid_t = uint
type off_t = ptr_int
type pid_t = int
type id_t = uint
type ssize_t = ptr_int
type daddr_t = int
type caddr_t = ptr[char]
type key_t = int
type u_int16_t = ushort
type u_int32_t = uint
type u_int64_t = ptr_uint
type register_t = ptr_int
type blkcnt_t = ptr_int
type fsblkcnt_t = ptr_uint
type fsfilcnt_t = ptr_uint
external function random() -> ptr_int
external function srandom(__seed: uint) -> void
external function initstate(__seed: uint, __statebuf: ptr[char], __statelen: ptr_uint) -> ptr[char]
external function setstate(__statebuf: ptr[char]) -> ptr[char]
struct random_data = c"struct random_data":
    fptr: ptr[int]
    rptr: ptr[int]
    state: ptr[int]
    rand_type: int
    rand_deg: int
    rand_sep: int
    end_ptr: ptr[int]
external function random_r(__buf: ptr[random_data], __result: ptr[int]) -> int
external function srandom_r(__seed: uint, __buf: ptr[random_data]) -> int
external function initstate_r(__seed: uint, __statebuf: ptr[char], __statelen: ptr_uint, __buf: ptr[random_data]) -> int
external function setstate_r(__statebuf: ptr[char], __buf: ptr[random_data]) -> int
external function rand() -> int
external function srand(__seed: uint) -> void
external function rand_r(__seed: ptr[uint]) -> int
external function drand48() -> double
external function erand48(__xsubi: ptr[ushort]) -> double
external function lrand48() -> ptr_int
external function nrand48(__xsubi: ptr[ushort]) -> ptr_int
external function mrand48() -> ptr_int
external function jrand48(__xsubi: ptr[ushort]) -> ptr_int
external function srand48(__seedval: ptr_int) -> void
external function seed48(__seed16v: ptr[ushort]) -> ptr[ushort]
external function lcong48(__param: ptr[ushort]) -> void
struct drand48_data = c"struct drand48_data":
    __x: array[ushort, 3]
    __old_x: array[ushort, 3]
    __c: ushort
    __init: ushort
    __a: ulong
external function drand48_r(__buffer: ptr[drand48_data], __result: ptr[double]) -> int
external function erand48_r(__xsubi: ptr[ushort], __buffer: ptr[drand48_data], __result: ptr[double]) -> int
external function lrand48_r(__buffer: ptr[drand48_data], __result: ptr[ptr_int]) -> int
external function nrand48_r(__xsubi: ptr[ushort], __buffer: ptr[drand48_data], __result: ptr[ptr_int]) -> int
external function mrand48_r(__buffer: ptr[drand48_data], __result: ptr[ptr_int]) -> int
external function jrand48_r(__xsubi: ptr[ushort], __buffer: ptr[drand48_data], __result: ptr[ptr_int]) -> int
external function srand48_r(__seedval: ptr_int, __buffer: ptr[drand48_data]) -> int
external function seed48_r(__seed16v: ptr[ushort], __buffer: ptr[drand48_data]) -> int
external function lcong48_r(__param: ptr[ushort], __buffer: ptr[drand48_data]) -> int
external function arc4random() -> uint
external function arc4random_buf(__buf: ptr[void], __size: ptr_uint) -> void
external function arc4random_uniform(__upper_bound: uint) -> uint
external function malloc(__size: ptr_uint) -> ptr[void]?
external function calloc(__nmemb: ptr_uint, __size: ptr_uint) -> ptr[void]?
external function realloc(__ptr: ptr[void]?, __size: ptr_uint) -> ptr[void]?
external function free(__ptr: ptr[void]?) -> void
external function reallocarray(__ptr: ptr[void]?, __nmemb: ptr_uint, __size: ptr_uint) -> ptr[void]?
external function valloc(__size: ptr_uint) -> ptr[void]
external function posix_memalign(__memptr: ptr[ptr[void]], __alignment: ptr_uint, __size: ptr_uint) -> int
external function aligned_alloc(__alignment: ptr_uint, __size: ptr_uint) -> ptr[void]?
external function abort() -> void
external function atexit(__func: fn() -> void) -> int
external function at_quick_exit(__func: fn() -> void) -> int
external function on_exit(__func: fn(arg0: int, arg1: ptr[void]) -> void, __arg: ptr[void]) -> int
external function exit(__status: int) -> void
external function quick_exit(__status: int) -> void
external function _Exit(__status: int) -> void
external function getenv(__name: cstr) -> ptr[char]
external function putenv(__string: ptr[char]) -> int
external function setenv(__name: cstr, __value: cstr, __replace: int) -> int
external function unsetenv(__name: cstr) -> int
external function clearenv() -> int
external function mktemp(__template: ptr[char]) -> ptr[char]
external function mkstemp(__template: ptr[char]) -> int
external function mkstemps(__template: ptr[char], __suffixlen: int) -> int
external function mkdtemp(__template: ptr[char]) -> ptr[char]
external function system(__command: cstr) -> int
external function realpath(__name: cstr, __resolved: ptr[char]) -> ptr[char]
type __compar_fn_t = fn(arg0: const_ptr[void], arg1: const_ptr[void]) -> int
external function bsearch(__key: const_ptr[void], __base: const_ptr[void], __nmemb: ptr_uint, __size: ptr_uint, __compar: fn(arg0: const_ptr[void], arg1: const_ptr[void]) -> int) -> ptr[void]
external function qsort(__base: ptr[void], __nmemb: ptr_uint, __size: ptr_uint, __compar: fn(arg0: const_ptr[void], arg1: const_ptr[void]) -> int) -> void
external function abs(__x: int) -> int
external function labs(__x: ptr_int) -> ptr_int
external function llabs(__x: long) -> long
external function div(__numer: int, __denom: int) -> div_t
external function ldiv(__numer: ptr_int, __denom: ptr_int) -> ldiv_t
external function lldiv(__numer: long, __denom: long) -> lldiv_t
external function ecvt(__value: double, __ndigit: int, __decpt: ptr[int], __sign: ptr[int]) -> ptr[char]
external function fcvt(__value: double, __ndigit: int, __decpt: ptr[int], __sign: ptr[int]) -> ptr[char]
external function gcvt(__value: double, __ndigit: int, __buf: ptr[char]) -> ptr[char]
external function ecvt_r(__value: double, __ndigit: int, __decpt: ptr[int], __sign: ptr[int], __buf: ptr[char], __len: ptr_uint) -> int
external function fcvt_r(__value: double, __ndigit: int, __decpt: ptr[int], __sign: ptr[int], __buf: ptr[char], __len: ptr_uint) -> int
external function mblen(__s: cstr, __n: ptr_uint) -> int
external function mbtowc(__pwc: ptr[int], __s: cstr, __n: ptr_uint) -> int
external function wctomb(__s: ptr[char], __wchar: int) -> int
external function mbstowcs(__pwcs: ptr[int], __s: cstr, __n: ptr_uint) -> ptr_uint
external function wcstombs(__s: ptr[char], __pwcs: const_ptr[int], __n: ptr_uint) -> ptr_uint
external function rpmatch(__response: cstr) -> int
external function getsubopt(__optionp: ptr[ptr[char]], __tokens: const_ptr[ptr[char]], __valuep: ptr[ptr[char]]) -> int
external function getloadavg(__loadavg: ptr[double], __nelem: int) -> int
const RAND_MAX: int = 2147483647
const EXIT_FAILURE: int = 1
const EXIT_SUCCESS: int = 0
