extern module std.c.libuv_system:
    opaque DIR = c"DIR"
    opaque addrinfo = c"struct addrinfo"
    opaque pthread_barrier_t = c"pthread_barrier_t"
    opaque pthread_cond_t = c"pthread_cond_t"
    opaque pthread_mutex_t = c"pthread_mutex_t"
    opaque pthread_rwlock_t = c"pthread_rwlock_t"
    opaque sem_t = c"sem_t"
    opaque sockaddr = c"struct sockaddr"
    opaque sockaddr_in = c"struct sockaddr_in"
    opaque sockaddr_in6 = c"struct sockaddr_in6"
    opaque sockaddr_storage = c"struct sockaddr_storage"
    opaque termios = c"struct termios"
    opaque uv__work = c"struct uv__work"