# generated by mtc bindgen from /home/teefan/Projects/Ruby/mt-lang/third_party/libuv-upstream/include/uv.h
external

link "uv"
include "uv.h"

union uv_handle_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_stream_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_tcp_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_udp_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_udp_send_s_u:
    addr: sockaddr
    storage: sockaddr_storage

union uv_tty_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_pipe_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_poll_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_prepare_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_check_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_idle_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_async_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_timer_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_timer_s_node:
    fd: int
    reserved: array[ptr[void], 4]

union uv_stdio_container_t_data:
    stream: ptr[uv_stream_t]
    fd: int

union uv_process_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_interface_address_s_address:
    address4: sockaddr_in
    address6: sockaddr_in6

union uv_interface_address_s_netmask:
    netmask4: sockaddr_in
    netmask6: sockaddr_in6

union uv_fs_event_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_fs_poll_s_u:
    fd: int
    reserved: array[ptr[void], 4]

union uv_signal_s_u:
    fd: int
    reserved: array[ptr[void], 4]

struct uv_signal_s_tree_entry:
    rbe_left: ptr[uv_signal_s]
    rbe_right: ptr[uv_signal_s]
    rbe_parent: ptr[uv_signal_s]
    rbe_color: int

union uv_loop_s_active_reqs:
    unused: ptr[void]
    count: uint

struct uv_loop_s_timer_heap:
    min: ptr[void]
    nelts: uint

struct sockaddr = c"struct sockaddr":
    sa_family: ushort
    sa_data: array[char, 14]

struct addrinfo = c"struct addrinfo":
    ai_flags: int
    ai_family: int
    ai_socktype: int
    ai_protocol: int
    ai_addrlen: uint
    ai_addr: ptr[sockaddr]
    ai_canonname: ptr[char]
    ai_next: ptr[addrinfo]

struct sockaddr_storage = c"struct sockaddr_storage":
    ss_family: ushort
    __ss_padding: array[char, 118]
    __ss_align: ptr_uint

opaque pthread_mutex_t = c"union pthread_mutex_t"
opaque pthread_rwlock_t = c"union pthread_rwlock_t"

struct sockaddr_in = c"struct sockaddr_in":
    sin_family: ushort
    sin_port: ushort
    sin_addr: uint
    sin_zero: array[ubyte, 8]

struct sockaddr_in6 = c"struct sockaddr_in6":
    sin6_family: ushort
    sin6_port: ushort
    sin6_flowinfo: uint
    sin6_addr: array[ubyte, 16]
    sin6_scope_id: uint

opaque sem_t = c"union sem_t"
opaque pthread_cond_t = c"union pthread_cond_t"
opaque pthread_barrier_t = c"union pthread_barrier_t"

struct uv__queue = c"struct uv__queue":
    next: ptr[uv__queue]
    prev: ptr[uv__queue]

struct uv__work = c"struct uv__work":
    work: fn(arg0: ptr[uv__work]) -> void
    done: fn(arg0: ptr[uv__work], arg1: int) -> void
    loop: ptr[uv_loop_s]
    wq: uv__queue

opaque uv__io_t = c"uv__io_t"
opaque uv_loop_t = c"uv_loop_t"

struct uv__io_s = c"uv__io_t":
    bits: ptr_uint
    pending_queue: uv__queue
    watcher_queue: uv__queue
    pevents: uint
    events: uint
    fd: int

struct uv_buf_t:
    base: ptr[char]
    len: ptr_uint

type uv_file = int
type uv_os_sock_t = int
type uv_os_fd_t = int
type uv_pid_t = int
type uv_once_t = int
type uv_thread_t = ptr_uint
type uv_mutex_t = pthread_mutex_t
type uv_rwlock_t = pthread_rwlock_t
type uv_sem_t = sem_t
type uv_cond_t = pthread_cond_t
type uv_key_t = uint
type uv_barrier_t = pthread_barrier_t
type uv_gid_t = uint
type uv_uid_t = uint

struct uv__dirent_t:
    d_ino: ptr_uint
    d_off: ptr_int
    d_reclen: ushort
    d_type: ubyte
    d_name: array[char, 256]

struct uv_lib_t:
    handle: ptr[void]
    errmsg: ptr[char]

enum uv_errno_t: int
    UV_E2BIG = -7
    UV_EACCES = -13
    UV_EADDRINUSE = -98
    UV_EADDRNOTAVAIL = -99
    UV_EAFNOSUPPORT = -97
    UV_EAGAIN = -11
    UV_EAI_ADDRFAMILY = -3000
    UV_EAI_AGAIN = -3001
    UV_EAI_BADFLAGS = -3002
    UV_EAI_BADHINTS = -3013
    UV_EAI_CANCELED = -3003
    UV_EAI_FAIL = -3004
    UV_EAI_FAMILY = -3005
    UV_EAI_MEMORY = -3006
    UV_EAI_NODATA = -3007
    UV_EAI_NONAME = -3008
    UV_EAI_OVERFLOW = -3009
    UV_EAI_PROTOCOL = -3014
    UV_EAI_SERVICE = -3010
    UV_EAI_SOCKTYPE = -3011
    UV_EALREADY = -114
    UV_EBADF = -9
    UV_EBUSY = -16
    UV_ECANCELED = -125
    UV_ECHARSET = -4080
    UV_ECONNABORTED = -103
    UV_ECONNREFUSED = -111
    UV_ECONNRESET = -104
    UV_EDESTADDRREQ = -89
    UV_EEXIST = -17
    UV_EFAULT = -14
    UV_EFBIG = -27
    UV_EHOSTUNREACH = -113
    UV_EINTR = -4
    UV_EINVAL = -22
    UV_EIO = -5
    UV_EISCONN = -106
    UV_EISDIR = -21
    UV_ELOOP = -40
    UV_EMFILE = -24
    UV_EMSGSIZE = -90
    UV_ENAMETOOLONG = -36
    UV_ENETDOWN = -100
    UV_ENETUNREACH = -101
    UV_ENFILE = -23
    UV_ENOBUFS = -105
    UV_ENODEV = -19
    UV_ENOENT = -2
    UV_ENOMEM = -12
    UV_ENONET = -64
    UV_ENOPROTOOPT = -92
    UV_ENOSPC = -28
    UV_ENOSYS = -38
    UV_ENOTCONN = -107
    UV_ENOTDIR = -20
    UV_ENOTEMPTY = -39
    UV_ENOTSOCK = -88
    UV_ENOTSUP = -95
    UV_EOVERFLOW = -75
    UV_EPERM = -1
    UV_EPIPE = -32
    UV_EPROTO = -71
    UV_EPROTONOSUPPORT = -93
    UV_EPROTOTYPE = -91
    UV_ERANGE = -34
    UV_EROFS = -30
    UV_ESHUTDOWN = -108
    UV_ESPIPE = -29
    UV_ESRCH = -3
    UV_ETIMEDOUT = -110
    UV_ETXTBSY = -26
    UV_EXDEV = -18
    UV_UNKNOWN = -4094
    UV_EOF = -4095
    UV_ENXIO = -6
    UV_EMLINK = -31
    UV_EHOSTDOWN = -112
    UV_EREMOTEIO = -121
    UV_ENOTTY = -25
    UV_EFTYPE = -4028
    UV_EILSEQ = -84
    UV_ESOCKTNOSUPPORT = -94
    UV_ENODATA = -61
    UV_EUNATCH = -49
    UV_ENOEXEC = -8
    UV_ERRNO_MAX = -4096

enum uv_handle_type: int
    UV_UNKNOWN_HANDLE = 0
    UV_ASYNC = 1
    UV_CHECK = 2
    UV_FS_EVENT = 3
    UV_FS_POLL = 4
    UV_HANDLE = 5
    UV_IDLE = 6
    UV_NAMED_PIPE = 7
    UV_POLL = 8
    UV_PREPARE = 9
    UV_PROCESS = 10
    UV_STREAM = 11
    UV_TCP = 12
    UV_TIMER = 13
    UV_TTY = 14
    UV_UDP = 15
    UV_SIGNAL = 16
    UV_FILE = 17
    UV_HANDLE_TYPE_MAX = 18

enum uv_req_type: int
    UV_UNKNOWN_REQ = 0
    UV_REQ = 1
    UV_CONNECT = 2
    UV_WRITE = 3
    UV_SHUTDOWN = 4
    UV_UDP_SEND = 5
    UV_FS = 6
    UV_WORK = 7
    UV_GETADDRINFO = 8
    UV_GETNAMEINFO = 9
    UV_RANDOM = 10
    UV_REQ_TYPE_MAX = 11

opaque uv_handle_t = c"uv_handle_t"
opaque uv_dir_t = c"uv_dir_t"
opaque uv_stream_t = c"uv_stream_t"
opaque uv_tcp_t = c"uv_tcp_t"
opaque uv_udp_t = c"uv_udp_t"
opaque uv_pipe_t = c"uv_pipe_t"
opaque uv_tty_t = c"uv_tty_t"
opaque uv_poll_t = c"uv_poll_t"
opaque uv_timer_t = c"uv_timer_t"
opaque uv_prepare_t = c"uv_prepare_t"
opaque uv_check_t = c"uv_check_t"
opaque uv_idle_t = c"uv_idle_t"
opaque uv_async_t = c"uv_async_t"
opaque uv_process_t = c"uv_process_t"
opaque uv_fs_event_t = c"uv_fs_event_t"
opaque uv_fs_poll_t = c"uv_fs_poll_t"
opaque uv_signal_t = c"uv_signal_t"
opaque uv_req_t = c"uv_req_t"
opaque uv_getaddrinfo_t = c"uv_getaddrinfo_t"
opaque uv_getnameinfo_t = c"uv_getnameinfo_t"
opaque uv_shutdown_t = c"uv_shutdown_t"
opaque uv_write_t = c"uv_write_t"
opaque uv_connect_t = c"uv_connect_t"
opaque uv_udp_send_t = c"uv_udp_send_t"
opaque uv_fs_t = c"uv_fs_t"
opaque uv_work_t = c"uv_work_t"
opaque uv_random_t = c"uv_random_t"
opaque uv_env_item_t = c"uv_env_item_t"
opaque uv_cpu_info_t = c"uv_cpu_info_t"
opaque uv_interface_address_t = c"uv_interface_address_t"
opaque uv_dirent_t = c"uv_dirent_t"
opaque uv_passwd_t = c"uv_passwd_t"
opaque uv_group_t = c"uv_group_t"
opaque uv_utsname_t = c"uv_utsname_t"
opaque uv_statfs_t = c"uv_statfs_t"
opaque uv_metrics_t = c"uv_metrics_t"

flags uv_loop_option: int
    UV_LOOP_BLOCK_SIGNAL = 0
    UV_METRICS_IDLE_TIME = 1
    UV_LOOP_USE_IO_URING_SQPOLL = 2

flags uv_run_mode: int
    UV_RUN_DEFAULT = 0
    UV_RUN_ONCE = 1
    UV_RUN_NOWAIT = 2

external function uv_version() -> uint
external function uv_version_string() -> cstr

type uv_malloc_func = fn(arg0: ptr_uint) -> ptr[void]
type uv_realloc_func = fn(arg0: ptr[void], arg1: ptr_uint) -> ptr[void]
type uv_calloc_func = fn(arg0: ptr_uint, arg1: ptr_uint) -> ptr[void]
type uv_free_func = fn(arg0: ptr[void]) -> void

external function uv_library_shutdown() -> void
external function uv_replace_allocator(malloc_func: fn(arg0: ptr_uint) -> ptr[void], realloc_func: fn(arg0: ptr[void], arg1: ptr_uint) -> ptr[void], calloc_func: fn(arg0: ptr_uint, arg1: ptr_uint) -> ptr[void], free_func: fn(arg0: ptr[void]) -> void) -> int
external function uv_default_loop() -> ptr[uv_loop_t]?
external function uv_loop_init(loop: ptr[uv_loop_t]) -> int
external function uv_loop_close(loop: ptr[uv_loop_t]) -> int
external function uv_loop_new() -> ptr[uv_loop_t]?
external function uv_loop_delete(arg0: ptr[uv_loop_t]) -> void
external function uv_loop_size() -> ptr_uint
external function uv_loop_alive(loop: const_ptr[uv_loop_t]) -> int
external function uv_loop_configure(loop: ptr[uv_loop_t], option: uv_loop_option, ...) -> int
external function uv_loop_fork(loop: ptr[uv_loop_t]) -> int
external function uv_run(arg0: ptr[uv_loop_t], mode: uv_run_mode) -> int
external function uv_stop(arg0: ptr[uv_loop_t]) -> void
external function uv_ref(arg0: ptr[uv_handle_t]) -> void
external function uv_unref(arg0: ptr[uv_handle_t]) -> void
external function uv_has_ref(arg0: const_ptr[uv_handle_t]) -> int
external function uv_update_time(arg0: ptr[uv_loop_t]) -> void
external function uv_now(arg0: const_ptr[uv_loop_t]) -> ulong
external function uv_backend_fd(arg0: const_ptr[uv_loop_t]) -> int
external function uv_backend_timeout(arg0: const_ptr[uv_loop_t]) -> int

type uv_alloc_cb = fn(arg0: ptr[uv_handle_t], arg1: ptr_uint, arg2: ptr[uv_buf_t]) -> void
type uv_read_cb = fn(arg0: ptr[uv_stream_t], arg1: ptr_int, arg2: const_ptr[uv_buf_t]) -> void
type uv_write_cb = fn(arg0: ptr[uv_write_t], arg1: int) -> void
type uv_connect_cb = fn(arg0: ptr[uv_connect_t], arg1: int) -> void
type uv_shutdown_cb = fn(arg0: ptr[uv_shutdown_t], arg1: int) -> void
type uv_connection_cb = fn(arg0: ptr[uv_stream_t], arg1: int) -> void
type uv_close_cb = fn(arg0: ptr[uv_handle_t]) -> void
type uv_poll_cb = fn(arg0: ptr[uv_poll_t], arg1: int, arg2: int) -> void
type uv_timer_cb = fn(arg0: ptr[uv_timer_t]) -> void
type uv_async_cb = fn(arg0: ptr[uv_async_t]) -> void
type uv_prepare_cb = fn(arg0: ptr[uv_prepare_t]) -> void
type uv_check_cb = fn(arg0: ptr[uv_check_t]) -> void
type uv_idle_cb = fn(arg0: ptr[uv_idle_t]) -> void
type uv_exit_cb = fn(arg0: ptr[uv_process_t], arg1: long, arg2: int) -> void
type uv_walk_cb = fn(arg0: ptr[uv_handle_t], arg1: ptr[void]) -> void
type uv_fs_cb = fn(arg0: ptr[uv_fs_t]) -> void
type uv_work_cb = fn(arg0: ptr[uv_work_t]) -> void
type uv_after_work_cb = fn(arg0: ptr[uv_work_t], arg1: int) -> void
type uv_getaddrinfo_cb = fn(arg0: ptr[uv_getaddrinfo_t], arg1: int, arg2: ptr[addrinfo]) -> void
type uv_getnameinfo_cb = fn(arg0: ptr[uv_getnameinfo_t], arg1: int, arg2: cstr, arg3: cstr) -> void
type uv_random_cb = fn(arg0: ptr[uv_random_t], arg1: int, arg2: ptr[void], arg3: ptr_uint) -> void

flags uv_clock_id: int
    UV_CLOCK_MONOTONIC = 0
    UV_CLOCK_REALTIME = 1

struct uv_timespec_t:
    tv_sec: ptr_int
    tv_nsec: ptr_int

struct uv_timespec64_t:
    tv_sec: ptr_int
    tv_nsec: int

struct uv_timeval_t:
    tv_sec: ptr_int
    tv_usec: ptr_int

struct uv_timeval64_t:
    tv_sec: ptr_int
    tv_usec: int

struct uv_stat_t:
    st_dev: ptr_uint
    st_mode: ptr_uint
    st_nlink: ptr_uint
    st_uid: ptr_uint
    st_gid: ptr_uint
    st_rdev: ptr_uint
    st_ino: ptr_uint
    st_size: ptr_uint
    st_blksize: ptr_uint
    st_blocks: ptr_uint
    st_flags: ptr_uint
    st_gen: ptr_uint
    st_atim: uv_timespec_t
    st_mtim: uv_timespec_t
    st_ctim: uv_timespec_t
    st_birthtim: uv_timespec_t

type uv_fs_event_cb = fn(arg0: ptr[uv_fs_event_t], arg1: cstr, arg2: int, arg3: int) -> void
type uv_fs_poll_cb = fn(arg0: ptr[uv_fs_poll_t], arg1: int, arg2: const_ptr[uv_stat_t], arg3: const_ptr[uv_stat_t]) -> void
type uv_signal_cb = fn(arg0: ptr[uv_signal_t], arg1: int) -> void

flags uv_membership: int
    UV_LEAVE_GROUP = 0
    UV_JOIN_GROUP = 1

external function uv_translate_sys_error(sys_errno: int) -> int
external function uv_strerror(err: int) -> cstr
external function uv_strerror_r(err: int, buf: ptr[char], buflen: ptr_uint) -> ptr[char]
external function uv_err_name(err: int) -> cstr
external function uv_err_name_r(err: int, buf: ptr[char], buflen: ptr_uint) -> ptr[char]

struct uv_req_s = c"uv_req_t":
    data: ptr[void]
    type_: uv_req_type
    reserved: array[ptr[void], 6]

external function uv_shutdown(req: ptr[uv_shutdown_t], handle: ptr[uv_stream_t], cb: fn(arg0: ptr[uv_shutdown_t], arg1: int) -> void) -> int

struct uv_shutdown_s = c"uv_shutdown_t":
    data: ptr[void]
    type_: uv_req_type
    reserved: array[ptr[void], 6]
    handle: ptr[uv_stream_t]
    cb: fn(arg0: ptr[uv_shutdown_t], arg1: int) -> void

struct uv_handle_s = c"uv_handle_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_handle_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint

external function uv_handle_size(type_: uv_handle_type) -> ptr_uint
external function uv_handle_get_type(handle: const_ptr[uv_handle_t]) -> uv_handle_type
external function uv_handle_type_name(type_: uv_handle_type) -> cstr
external function uv_handle_get_data(handle: const_ptr[uv_handle_t]) -> ptr[void]?
external function uv_handle_get_loop(handle: const_ptr[uv_handle_t]) -> ptr[uv_loop_t]
external function uv_handle_set_data(handle: ptr[uv_handle_t], data: ptr[void]) -> void
external function uv_req_size(type_: uv_req_type) -> ptr_uint
external function uv_req_get_data(req: const_ptr[uv_req_t]) -> ptr[void]?
external function uv_req_set_data(req: ptr[uv_req_t], data: ptr[void]) -> void
external function uv_req_get_type(req: const_ptr[uv_req_t]) -> uv_req_type
external function uv_req_type_name(type_: uv_req_type) -> cstr
external function uv_is_active(handle: const_ptr[uv_handle_t]) -> int
external function uv_walk(loop: ptr[uv_loop_t], walk_cb: fn(arg0: ptr[uv_handle_t], arg1: ptr[void]) -> void, arg: ptr[void]) -> void
external function uv_close(handle: ptr[uv_handle_t], close_cb: fn(arg0: ptr[uv_handle_t]) -> void) -> void
external function uv_send_buffer_size(handle: ptr[uv_handle_t], value: ptr[int]) -> int
external function uv_recv_buffer_size(handle: ptr[uv_handle_t], value: ptr[int]) -> int
external function uv_fileno(handle: const_ptr[uv_handle_t], fd: ptr[uv_os_fd_t]) -> int
external function uv_buf_init(base: ptr[char], len: uint) -> uv_buf_t
external function uv_pipe(fds: ptr[uv_file], read_flags: int, write_flags: int) -> int
external function uv_socketpair(type_: int, protocol: int, socket_vector: ptr[uv_os_sock_t], flags0: int, flags1: int) -> int

struct uv_stream_s = c"uv_stream_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_stream_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    write_queue_size: ptr_uint
    alloc_cb: fn(arg0: ptr[uv_handle_t], arg1: ptr_uint, arg2: ptr[uv_buf_t]) -> void
    read_cb: fn(arg0: ptr[uv_stream_t], arg1: ptr_int, arg2: const_ptr[uv_buf_t]) -> void
    connect_req: ptr[uv_connect_t]
    shutdown_req: ptr[uv_shutdown_t]
    io_watcher: uv__io_s
    write_queue: uv__queue
    write_completed_queue: uv__queue
    connection_cb: fn(arg0: ptr[uv_stream_t], arg1: int) -> void
    delayed_error: int
    accepted_fd: int
    queued_fds: ptr[void]

external function uv_stream_get_write_queue_size(stream: const_ptr[uv_stream_t]) -> ptr_uint
external function uv_listen(stream: ptr[uv_stream_t], backlog: int, cb: fn(arg0: ptr[uv_stream_t], arg1: int) -> void) -> int
external function uv_accept(server: ptr[uv_stream_t], client: ptr[uv_stream_t]) -> int
external function uv_read_start(arg0: ptr[uv_stream_t], alloc_cb: fn(arg0: ptr[uv_handle_t], arg1: ptr_uint, arg2: ptr[uv_buf_t]) -> void, read_cb: fn(arg0: ptr[uv_stream_t], arg1: ptr_int, arg2: const_ptr[uv_buf_t]) -> void) -> int
external function uv_read_stop(arg0: ptr[uv_stream_t]) -> int
external function uv_write(req: ptr[uv_write_t], handle: ptr[uv_stream_t], bufs: const_ptr[uv_buf_t], nbufs: uint, cb: fn(arg0: ptr[uv_write_t], arg1: int) -> void) -> int
external function uv_write2(req: ptr[uv_write_t], handle: ptr[uv_stream_t], bufs: const_ptr[uv_buf_t], nbufs: uint, send_handle: ptr[uv_stream_t], cb: fn(arg0: ptr[uv_write_t], arg1: int) -> void) -> int
external function uv_try_write(handle: ptr[uv_stream_t], bufs: const_ptr[uv_buf_t], nbufs: uint) -> int
external function uv_try_write2(handle: ptr[uv_stream_t], bufs: const_ptr[uv_buf_t], nbufs: uint, send_handle: ptr[uv_stream_t]) -> int

struct uv_write_s = c"uv_write_t":
    data: ptr[void]
    type_: uv_req_type
    reserved: array[ptr[void], 6]
    cb: fn(arg0: ptr[uv_write_t], arg1: int) -> void
    send_handle: ptr[uv_stream_t]
    handle: ptr[uv_stream_t]
    queue: uv__queue
    write_index: uint
    bufs: ptr[uv_buf_t]
    nbufs: uint
    error: int
    bufsml: array[uv_buf_t, 4]

external function uv_is_readable(handle: const_ptr[uv_stream_t]) -> int
external function uv_is_writable(handle: const_ptr[uv_stream_t]) -> int
external function uv_stream_set_blocking(handle: ptr[uv_stream_t], blocking: int) -> int
external function uv_is_closing(handle: const_ptr[uv_handle_t]) -> int

struct uv_tcp_s = c"uv_tcp_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_tcp_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    write_queue_size: ptr_uint
    alloc_cb: fn(arg0: ptr[uv_handle_t], arg1: ptr_uint, arg2: ptr[uv_buf_t]) -> void
    read_cb: fn(arg0: ptr[uv_stream_t], arg1: ptr_int, arg2: const_ptr[uv_buf_t]) -> void
    connect_req: ptr[uv_connect_t]
    shutdown_req: ptr[uv_shutdown_t]
    io_watcher: uv__io_s
    write_queue: uv__queue
    write_completed_queue: uv__queue
    connection_cb: fn(arg0: ptr[uv_stream_t], arg1: int) -> void
    delayed_error: int
    accepted_fd: int
    queued_fds: ptr[void]

external function uv_tcp_init(arg0: ptr[uv_loop_t], handle: ptr[uv_tcp_t]) -> int
external function uv_tcp_init_ex(arg0: ptr[uv_loop_t], handle: ptr[uv_tcp_t], flags_: uint) -> int
external function uv_tcp_open(handle: ptr[uv_tcp_t], sock: int) -> int
external function uv_tcp_nodelay(handle: ptr[uv_tcp_t], enable: int) -> int
external function uv_tcp_keepalive(handle: ptr[uv_tcp_t], enable: int, delay: uint) -> int
external function uv_tcp_keepalive_ex(handle: ptr[uv_tcp_t], on: int, idle: uint, intvl: uint, cnt: uint) -> int
external function uv_tcp_simultaneous_accepts(handle: ptr[uv_tcp_t], enable: int) -> int

flags uv_tcp_flags: int
    UV_TCP_IPV6ONLY = 1
    UV_TCP_REUSEPORT = 2

external function uv_tcp_bind(handle: ptr[uv_tcp_t], addr: const_ptr[sockaddr], flags_: uint) -> int
external function uv_tcp_getsockname(handle: const_ptr[uv_tcp_t], name: ptr[sockaddr], namelen: ptr[int]) -> int
external function uv_tcp_getpeername(handle: const_ptr[uv_tcp_t], name: ptr[sockaddr], namelen: ptr[int]) -> int
external function uv_tcp_close_reset(handle: ptr[uv_tcp_t], close_cb: fn(arg0: ptr[uv_handle_t]) -> void) -> int
external function uv_tcp_connect(req: ptr[uv_connect_t], handle: ptr[uv_tcp_t], addr: const_ptr[sockaddr], cb: fn(arg0: ptr[uv_connect_t], arg1: int) -> void) -> int

struct uv_connect_s = c"uv_connect_t":
    data: ptr[void]
    type_: uv_req_type
    reserved: array[ptr[void], 6]
    cb: fn(arg0: ptr[uv_connect_t], arg1: int) -> void
    handle: ptr[uv_stream_t]
    queue: uv__queue

flags uv_udp_flags: int
    UV_UDP_IPV6ONLY = 1
    UV_UDP_PARTIAL = 2
    UV_UDP_REUSEADDR = 4
    UV_UDP_MMSG_CHUNK = 8
    UV_UDP_MMSG_FREE = 16
    UV_UDP_LINUX_RECVERR = 32
    UV_UDP_REUSEPORT = 64
    UV_UDP_RECVMMSG = 256

type uv_udp_send_cb = fn(arg0: ptr[uv_udp_send_t], arg1: int) -> void
type uv_udp_recv_cb = fn(arg0: ptr[uv_udp_t], arg1: ptr_int, arg2: const_ptr[uv_buf_t], arg3: const_ptr[sockaddr], arg4: uint) -> void

struct uv_udp_s = c"uv_udp_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_udp_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    send_queue_size: ptr_uint
    send_queue_count: ptr_uint
    alloc_cb: fn(arg0: ptr[uv_handle_t], arg1: ptr_uint, arg2: ptr[uv_buf_t]) -> void
    recv_cb: fn(arg0: ptr[uv_udp_t], arg1: ptr_int, arg2: const_ptr[uv_buf_t], arg3: const_ptr[sockaddr], arg4: uint) -> void
    io_watcher: uv__io_s
    write_queue: uv__queue
    write_completed_queue: uv__queue

struct uv_udp_send_s = c"uv_udp_send_t":
    data: ptr[void]
    type_: uv_req_type
    reserved: array[ptr[void], 6]
    handle: ptr[uv_udp_t]
    cb: fn(arg0: ptr[uv_udp_send_t], arg1: int) -> void
    queue: uv__queue
    u: uv_udp_send_s_u
    nbufs: uint
    bufs: ptr[uv_buf_t]
    status: ptr_int
    send_cb: fn(arg0: ptr[uv_udp_send_t], arg1: int) -> void
    bufsml: array[uv_buf_t, 4]

external function uv_udp_init(arg0: ptr[uv_loop_t], handle: ptr[uv_udp_t]) -> int
external function uv_udp_init_ex(arg0: ptr[uv_loop_t], handle: ptr[uv_udp_t], flags_: uint) -> int
external function uv_udp_open(handle: ptr[uv_udp_t], sock: int) -> int
external function uv_udp_open_ex(handle: ptr[uv_udp_t], sock: int, flags_: uint) -> int
external function uv_udp_bind(handle: ptr[uv_udp_t], addr: const_ptr[sockaddr], flags_: uint) -> int
external function uv_udp_connect(handle: ptr[uv_udp_t], addr: const_ptr[sockaddr]) -> int
external function uv_udp_getpeername(handle: const_ptr[uv_udp_t], name: ptr[sockaddr], namelen: ptr[int]) -> int
external function uv_udp_getsockname(handle: const_ptr[uv_udp_t], name: ptr[sockaddr], namelen: ptr[int]) -> int
external function uv_udp_set_membership(handle: ptr[uv_udp_t], multicast_addr: cstr, interface_addr: cstr, membership: uv_membership) -> int
external function uv_udp_set_source_membership(handle: ptr[uv_udp_t], multicast_addr: cstr, interface_addr: cstr, source_addr: cstr, membership: uv_membership) -> int
external function uv_udp_set_multicast_loop(handle: ptr[uv_udp_t], on: int) -> int
external function uv_udp_set_multicast_ttl(handle: ptr[uv_udp_t], ttl: int) -> int
external function uv_udp_set_multicast_interface(handle: ptr[uv_udp_t], interface_addr: cstr) -> int
external function uv_udp_set_broadcast(handle: ptr[uv_udp_t], on: int) -> int
external function uv_udp_set_ttl(handle: ptr[uv_udp_t], ttl: int) -> int
external function uv_udp_send(req: ptr[uv_udp_send_t], handle: ptr[uv_udp_t], bufs: const_ptr[uv_buf_t], nbufs: uint, addr: const_ptr[sockaddr]?, send_cb: fn(arg0: ptr[uv_udp_send_t], arg1: int) -> void) -> int
external function uv_udp_try_send(handle: ptr[uv_udp_t], bufs: const_ptr[uv_buf_t], nbufs: uint, addr: const_ptr[sockaddr]?) -> int
external function uv_udp_try_send2(handle: ptr[uv_udp_t], count: uint, bufs: ptr[ptr[uv_buf_t]], nbufs: ptr[uint], addrs: ptr[ptr[sockaddr]], flags_: uint) -> int
external function uv_udp_recv_start(handle: ptr[uv_udp_t], alloc_cb: fn(arg0: ptr[uv_handle_t], arg1: ptr_uint, arg2: ptr[uv_buf_t]) -> void, recv_cb: fn(arg0: ptr[uv_udp_t], arg1: ptr_int, arg2: const_ptr[uv_buf_t], arg3: const_ptr[sockaddr], arg4: uint) -> void) -> int
external function uv_udp_using_recvmmsg(handle: const_ptr[uv_udp_t]) -> int
external function uv_udp_recv_stop(handle: ptr[uv_udp_t]) -> int
external function uv_udp_get_send_queue_size(handle: const_ptr[uv_udp_t]) -> ptr_uint
external function uv_udp_get_send_queue_count(handle: const_ptr[uv_udp_t]) -> ptr_uint

struct uv_tty_s = c"uv_tty_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_tty_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    write_queue_size: ptr_uint
    alloc_cb: fn(arg0: ptr[uv_handle_t], arg1: ptr_uint, arg2: ptr[uv_buf_t]) -> void
    read_cb: fn(arg0: ptr[uv_stream_t], arg1: ptr_int, arg2: const_ptr[uv_buf_t]) -> void
    connect_req: ptr[uv_connect_t]
    shutdown_req: ptr[uv_shutdown_t]
    io_watcher: uv__io_s
    write_queue: uv__queue
    write_completed_queue: uv__queue
    connection_cb: fn(arg0: ptr[uv_stream_t], arg1: int) -> void
    delayed_error: int
    accepted_fd: int
    queued_fds: ptr[void]
    orig_termios: void
    mode: int

enum uv_tty_mode_t: int
    UV_TTY_MODE_NORMAL = 0
    UV_TTY_MODE_RAW = 1
    UV_TTY_MODE_IO = 2
    UV_TTY_MODE_RAW_VT = 3

flags uv_tty_vtermstate_t: int
    UV_TTY_SUPPORTED = 0
    UV_TTY_UNSUPPORTED = 1

external function uv_tty_init(arg0: ptr[uv_loop_t], arg1: ptr[uv_tty_t], fd: int, readable: int) -> int
external function uv_tty_set_mode(arg0: ptr[uv_tty_t], mode: uv_tty_mode_t) -> int
external function uv_tty_reset_mode() -> int
external function uv_tty_get_winsize(arg0: ptr[uv_tty_t], width: ptr[int], height: ptr[int]) -> int
external function uv_tty_set_vterm_state(state: uv_tty_vtermstate_t) -> void
external function uv_tty_get_vterm_state(state: ptr[uv_tty_vtermstate_t]) -> int
external function uv_guess_handle(file: int) -> uv_handle_type

struct uv_pipe_s = c"uv_pipe_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_pipe_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    write_queue_size: ptr_uint
    alloc_cb: fn(arg0: ptr[uv_handle_t], arg1: ptr_uint, arg2: ptr[uv_buf_t]) -> void
    read_cb: fn(arg0: ptr[uv_stream_t], arg1: ptr_int, arg2: const_ptr[uv_buf_t]) -> void
    connect_req: ptr[uv_connect_t]
    shutdown_req: ptr[uv_shutdown_t]
    io_watcher: uv__io_s
    write_queue: uv__queue
    write_completed_queue: uv__queue
    connection_cb: fn(arg0: ptr[uv_stream_t], arg1: int) -> void
    delayed_error: int
    accepted_fd: int
    queued_fds: ptr[void]
    ipc: int
    pipe_fname: cstr

external function uv_pipe_init(arg0: ptr[uv_loop_t], handle: ptr[uv_pipe_t], ipc: int) -> int
external function uv_pipe_open(arg0: ptr[uv_pipe_t], file: int) -> int
external function uv_pipe_bind(handle: ptr[uv_pipe_t], name: cstr) -> int
external function uv_pipe_bind2(handle: ptr[uv_pipe_t], name: cstr, namelen: ptr_uint, flags_: uint) -> int
external function uv_pipe_connect(req: ptr[uv_connect_t], handle: ptr[uv_pipe_t], name: cstr, cb: fn(arg0: ptr[uv_connect_t], arg1: int) -> void) -> void
external function uv_pipe_connect2(req: ptr[uv_connect_t], handle: ptr[uv_pipe_t], name: cstr, namelen: ptr_uint, flags_: uint, cb: fn(arg0: ptr[uv_connect_t], arg1: int) -> void) -> int
external function uv_pipe_getsockname(handle: const_ptr[uv_pipe_t], buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_pipe_getpeername(handle: const_ptr[uv_pipe_t], buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_pipe_pending_instances(handle: ptr[uv_pipe_t], count: int) -> void
external function uv_pipe_pending_count(handle: ptr[uv_pipe_t]) -> int
external function uv_pipe_pending_type(handle: ptr[uv_pipe_t]) -> uv_handle_type
external function uv_pipe_chmod(handle: ptr[uv_pipe_t], flags_: int) -> int

struct uv_poll_s = c"uv_poll_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_poll_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    poll_cb: fn(arg0: ptr[uv_poll_t], arg1: int, arg2: int) -> void
    io_watcher: uv__io_s

flags uv_poll_event: int
    UV_READABLE = 1
    UV_WRITABLE = 2
    UV_DISCONNECT = 4
    UV_PRIORITIZED = 8

external function uv_poll_init(loop: ptr[uv_loop_t], handle: ptr[uv_poll_t], fd: int) -> int
external function uv_poll_init_socket(loop: ptr[uv_loop_t], handle: ptr[uv_poll_t], socket: int) -> int
external function uv_poll_start(handle: ptr[uv_poll_t], events: int, cb: fn(arg0: ptr[uv_poll_t], arg1: int, arg2: int) -> void) -> int
external function uv_poll_stop(handle: ptr[uv_poll_t]) -> int

struct uv_prepare_s = c"uv_prepare_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_prepare_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    prepare_cb: fn(arg0: ptr[uv_prepare_t]) -> void
    queue: uv__queue

external function uv_prepare_init(arg0: ptr[uv_loop_t], prepare: ptr[uv_prepare_t]) -> int
external function uv_prepare_start(prepare: ptr[uv_prepare_t], cb: fn(arg0: ptr[uv_prepare_t]) -> void) -> int
external function uv_prepare_stop(prepare: ptr[uv_prepare_t]) -> int

struct uv_check_s = c"uv_check_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_check_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    check_cb: fn(arg0: ptr[uv_check_t]) -> void
    queue: uv__queue

external function uv_check_init(arg0: ptr[uv_loop_t], check: ptr[uv_check_t]) -> int
external function uv_check_start(check: ptr[uv_check_t], cb: fn(arg0: ptr[uv_check_t]) -> void) -> int
external function uv_check_stop(check: ptr[uv_check_t]) -> int

struct uv_idle_s = c"uv_idle_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_idle_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    idle_cb: fn(arg0: ptr[uv_idle_t]) -> void
    queue: uv__queue

external function uv_idle_init(arg0: ptr[uv_loop_t], idle: ptr[uv_idle_t]) -> int
external function uv_idle_start(idle: ptr[uv_idle_t], cb: fn(arg0: ptr[uv_idle_t]) -> void) -> int
external function uv_idle_stop(idle: ptr[uv_idle_t]) -> int

struct uv_async_s = c"uv_async_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_async_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    async_cb: fn(arg0: ptr[uv_async_t]) -> void
    queue: uv__queue
    pending: int

external function uv_async_init(arg0: ptr[uv_loop_t], async_: ptr[uv_async_t], async_cb: fn(arg0: ptr[uv_async_t]) -> void) -> int
external function uv_async_send(async_: ptr[uv_async_t]) -> int

struct uv_timer_s = c"uv_timer_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_timer_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    timer_cb: fn(arg0: ptr[uv_timer_t]) -> void
    node: uv_timer_s_node
    timeout: ptr_uint
    repeat: ptr_uint
    start_id: ptr_uint

external function uv_timer_init(arg0: ptr[uv_loop_t], handle: ptr[uv_timer_t]) -> int
external function uv_timer_start(handle: ptr[uv_timer_t], cb: fn(arg0: ptr[uv_timer_t]) -> void, timeout: ptr_uint, repeat: ptr_uint) -> int
external function uv_timer_stop(handle: ptr[uv_timer_t]) -> int
external function uv_timer_again(handle: ptr[uv_timer_t]) -> int
external function uv_timer_set_repeat(handle: ptr[uv_timer_t], repeat: ptr_uint) -> void
external function uv_timer_get_repeat(handle: const_ptr[uv_timer_t]) -> ulong
external function uv_timer_get_due_in(handle: const_ptr[uv_timer_t]) -> ulong

struct uv_getaddrinfo_s = c"uv_getaddrinfo_t":
    data: ptr[void]
    type_: uv_req_type
    reserved: array[ptr[void], 6]
    loop: ptr[uv_loop_t]
    work_req: uv__work
    cb: fn(arg0: ptr[uv_getaddrinfo_t], arg1: int, arg2: ptr[addrinfo]) -> void
    hints: ptr[addrinfo]
    hostname: ptr[char]
    service: ptr[char]
    addrinfo: ptr[addrinfo]
    retcode: int

external function uv_getaddrinfo(loop: ptr[uv_loop_t], req: ptr[uv_getaddrinfo_t], getaddrinfo_cb: fn(arg0: ptr[uv_getaddrinfo_t], arg1: int, arg2: ptr[addrinfo]) -> void, node: cstr?, service: cstr?, hints: const_ptr[addrinfo]?) -> int
external function uv_freeaddrinfo(ai: ptr[addrinfo]?) -> void

struct uv_getnameinfo_s = c"uv_getnameinfo_t":
    data: ptr[void]
    type_: uv_req_type
    reserved: array[ptr[void], 6]
    loop: ptr[uv_loop_t]
    work_req: uv__work
    getnameinfo_cb: fn(arg0: ptr[uv_getnameinfo_t], arg1: int, arg2: cstr, arg3: cstr) -> void
    storage: sockaddr_storage
    flags_: int
    host: array[char, 1025]
    service: array[char, 32]
    retcode: int

external function uv_getnameinfo(loop: ptr[uv_loop_t], req: ptr[uv_getnameinfo_t], getnameinfo_cb: fn(arg0: ptr[uv_getnameinfo_t], arg1: int, arg2: cstr, arg3: cstr) -> void, addr: const_ptr[sockaddr], flags_: int) -> int

flags uv_stdio_flags: int
    UV_IGNORE = 0
    UV_CREATE_PIPE = 1
    UV_INHERIT_FD = 2
    UV_INHERIT_STREAM = 4
    UV_READABLE_PIPE = 16
    UV_WRITABLE_PIPE = 32
    UV_NONBLOCK_PIPE = 64
    UV_OVERLAPPED_PIPE = 64

struct uv_stdio_container_t:
    flags_: uv_stdio_flags
    data: uv_stdio_container_t_data

struct uv_process_options_t:
    exit_cb: fn(arg0: ptr[uv_process_t], arg1: long, arg2: int) -> void
    file: cstr
    args: ptr[ptr[char]]
    env: ptr[ptr[char]]
    cwd: cstr
    flags_: uint
    stdio_count: int
    stdio: ptr[uv_stdio_container_t]
    uid: uint
    gid: uint

flags uv_process_flags: int
    UV_PROCESS_SETUID = 1
    UV_PROCESS_SETGID = 2
    UV_PROCESS_WINDOWS_VERBATIM_ARGUMENTS = 4
    UV_PROCESS_DETACHED = 8
    UV_PROCESS_WINDOWS_HIDE = 16
    UV_PROCESS_WINDOWS_HIDE_CONSOLE = 32
    UV_PROCESS_WINDOWS_HIDE_GUI = 64
    UV_PROCESS_WINDOWS_FILE_PATH_EXACT_NAME = 128

struct uv_process_s = c"uv_process_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_process_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    exit_cb: fn(arg0: ptr[uv_process_t], arg1: long, arg2: int) -> void
    pid: int
    queue: uv__queue
    status: int

external function uv_spawn(loop: ptr[uv_loop_t], handle: ptr[uv_process_t], options: const_ptr[uv_process_options_t]) -> int
external function uv_process_kill(arg0: ptr[uv_process_t], signum: int) -> int
external function uv_kill(pid: int, signum: int) -> int
external function uv_process_get_pid(arg0: const_ptr[uv_process_t]) -> uv_pid_t

struct uv_work_s = c"uv_work_t":
    data: ptr[void]
    type_: uv_req_type
    reserved: array[ptr[void], 6]
    loop: ptr[uv_loop_t]
    work_cb: fn(arg0: ptr[uv_work_t]) -> void
    after_work_cb: fn(arg0: ptr[uv_work_t], arg1: int) -> void
    work_req: uv__work

external function uv_queue_work(loop: ptr[uv_loop_t], req: ptr[uv_work_t], work_cb: fn(arg0: ptr[uv_work_t]) -> void, after_work_cb: fn(arg0: ptr[uv_work_t], arg1: int) -> void) -> int
external function uv_cancel(req: ptr[uv_req_t]) -> int

struct uv_cpu_times_s = c"struct uv_cpu_times_s":
    user: ptr_uint
    nice: ptr_uint
    sys: ptr_uint
    idle: ptr_uint
    irq: ptr_uint

struct uv_cpu_info_s = c"uv_cpu_info_t":
    model: cstr
    speed: int
    cpu_times: uv_cpu_times_s

struct uv_interface_address_s = c"uv_interface_address_t":
    name: ptr[char]
    phys_addr: array[char, 6]
    is_internal: int
    address: uv_interface_address_s_address
    netmask: uv_interface_address_s_netmask

struct uv_passwd_s = c"uv_passwd_t":
    username: ptr[char]
    uid: ptr_uint
    gid: ptr_uint
    shell: ptr[char]
    homedir: ptr[char]

struct uv_group_s = c"uv_group_t":
    groupname: ptr[char]
    gid: ptr_uint
    members: ptr[ptr[char]]

struct uv_utsname_s = c"uv_utsname_t":
    sysname: array[char, 256]
    release: array[char, 256]
    version: array[char, 256]
    machine: array[char, 256]

struct uv_statfs_s = c"uv_statfs_t":
    f_type: ptr_uint
    f_bsize: ptr_uint
    f_blocks: ptr_uint
    f_bfree: ptr_uint
    f_bavail: ptr_uint
    f_files: ptr_uint
    f_ffree: ptr_uint
    f_frsize: ptr_uint
    f_spare: array[ulong, 3]

enum uv_dirent_type_t: int
    UV_DIRENT_UNKNOWN = 0
    UV_DIRENT_FILE = 1
    UV_DIRENT_DIR = 2
    UV_DIRENT_LINK = 3
    UV_DIRENT_FIFO = 4
    UV_DIRENT_SOCKET = 5
    UV_DIRENT_CHAR = 6
    UV_DIRENT_BLOCK = 7

struct uv_dirent_s = c"uv_dirent_t":
    name: cstr
    type_: uv_dirent_type_t

external function uv_setup_args(argc: int, argv: ptr[ptr[char]]) -> ptr[ptr[char]]
external function uv_get_process_title(buffer: ptr[char], size: ptr_uint) -> int
external function uv_set_process_title(title: cstr) -> int
external function uv_resident_set_memory(rss: ptr[ptr_uint]) -> int
external function uv_uptime(uptime: ptr[double]) -> int
external function uv_get_osfhandle(fd: int) -> uv_os_fd_t
external function uv_open_osfhandle(os_fd: int) -> int

struct uv_rusage_t:
    ru_utime: uv_timeval_t
    ru_stime: uv_timeval_t
    ru_maxrss: ptr_uint
    ru_ixrss: ptr_uint
    ru_idrss: ptr_uint
    ru_isrss: ptr_uint
    ru_minflt: ptr_uint
    ru_majflt: ptr_uint
    ru_nswap: ptr_uint
    ru_inblock: ptr_uint
    ru_oublock: ptr_uint
    ru_msgsnd: ptr_uint
    ru_msgrcv: ptr_uint
    ru_nsignals: ptr_uint
    ru_nvcsw: ptr_uint
    ru_nivcsw: ptr_uint

external function uv_getrusage(rusage: ptr[uv_rusage_t]) -> int
external function uv_getrusage_thread(rusage: ptr[uv_rusage_t]) -> int
external function uv_os_homedir(buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_os_tmpdir(buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_os_get_passwd(pwd: ptr[uv_passwd_t]) -> int
external function uv_os_free_passwd(pwd: ptr[uv_passwd_t]) -> void
external function uv_os_get_passwd2(pwd: ptr[uv_passwd_t], uid: uint) -> int
external function uv_os_get_group(grp: ptr[uv_group_t], gid: uint) -> int
external function uv_os_free_group(grp: ptr[uv_group_t]) -> void
external function uv_os_getpid() -> uv_pid_t
external function uv_os_getppid() -> uv_pid_t
external function uv_os_getpriority(pid: int, priority: ptr[int]) -> int
external function uv_os_setpriority(pid: int, priority: int) -> int
external function uv_thread_getpriority(tid: ptr_uint, priority: ptr[int]) -> int
external function uv_thread_setpriority(tid: ptr_uint, priority: int) -> int
external function uv_available_parallelism() -> uint
external function uv_cpu_info(cpu_infos: ptr[ptr[uv_cpu_info_t]], count: ptr[int]) -> int
external function uv_free_cpu_info(cpu_infos: ptr[uv_cpu_info_t], count: int) -> void
external function uv_cpumask_size() -> int
external function uv_interface_addresses(addresses: ptr[ptr[uv_interface_address_t]], count: ptr[int]) -> int
external function uv_free_interface_addresses(addresses: ptr[uv_interface_address_t], count: int) -> void

struct uv_env_item_s = c"uv_env_item_t":
    name: ptr[char]
    value: ptr[char]

external function uv_os_environ(envitems: ptr[ptr[uv_env_item_t]], count: ptr[int]) -> int
external function uv_os_free_environ(envitems: ptr[uv_env_item_t], count: int) -> void
external function uv_os_getenv(name: cstr, buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_os_setenv(name: cstr, value: cstr) -> int
external function uv_os_unsetenv(name: cstr) -> int
external function uv_os_gethostname(buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_os_uname(buffer: ptr[uv_utsname_t]) -> int

struct uv_metrics_s = c"uv_metrics_t":
    loop_count: ptr_uint
    events: ptr_uint
    events_waiting: ptr_uint
    reserved: array[ptr[ulong], 13]

external function uv_metrics_info(loop: ptr[uv_loop_t], metrics: ptr[uv_metrics_t]) -> int
external function uv_metrics_idle_time(loop: ptr[uv_loop_t]) -> ulong

enum uv_fs_type: int
    UV_FS_UNKNOWN = -1
    UV_FS_CUSTOM = 0
    UV_FS_OPEN = 1
    UV_FS_CLOSE = 2
    UV_FS_READ = 3
    UV_FS_WRITE = 4
    UV_FS_SENDFILE = 5
    UV_FS_STAT = 6
    UV_FS_LSTAT = 7
    UV_FS_FSTAT = 8
    UV_FS_FTRUNCATE = 9
    UV_FS_UTIME = 10
    UV_FS_FUTIME = 11
    UV_FS_ACCESS = 12
    UV_FS_CHMOD = 13
    UV_FS_FCHMOD = 14
    UV_FS_FSYNC = 15
    UV_FS_FDATASYNC = 16
    UV_FS_UNLINK = 17
    UV_FS_RMDIR = 18
    UV_FS_MKDIR = 19
    UV_FS_MKDTEMP = 20
    UV_FS_RENAME = 21
    UV_FS_SCANDIR = 22
    UV_FS_LINK = 23
    UV_FS_SYMLINK = 24
    UV_FS_READLINK = 25
    UV_FS_CHOWN = 26
    UV_FS_FCHOWN = 27
    UV_FS_REALPATH = 28
    UV_FS_COPYFILE = 29
    UV_FS_LCHOWN = 30
    UV_FS_OPENDIR = 31
    UV_FS_READDIR = 32
    UV_FS_CLOSEDIR = 33
    UV_FS_STATFS = 34
    UV_FS_MKSTEMP = 35
    UV_FS_LUTIME = 36

struct uv_dir_s = c"uv_dir_t":
    dirents: ptr[uv_dirent_t]
    nentries: ptr_uint
    reserved: array[ptr[void], 4]
    dir: ptr[void]

struct uv_fs_s = c"uv_fs_t":
    data: ptr[void]
    type_: uv_req_type
    reserved: array[ptr[void], 6]
    fs_type: uv_fs_type
    loop: ptr[uv_loop_t]?
    cb: uv_fs_cb?
    result: ptr_int
    ptr: ptr[void]
    path: cstr
    statbuf: uv_stat_t
    new_path: cstr
    file: int
    flags_: int
    mode: uint
    nbufs: uint
    bufs: ptr[uv_buf_t]
    off: ptr_int
    uid: uint
    gid: uint
    atime: double
    mtime: double
    work_req: uv__work
    bufsml: array[uv_buf_t, 4]

external function uv_fs_get_type(arg0: const_ptr[uv_fs_t]) -> uv_fs_type
external function uv_fs_get_result(arg0: const_ptr[uv_fs_t]) -> ptr_int
external function uv_fs_get_system_error(arg0: const_ptr[uv_fs_t]) -> int
external function uv_fs_get_ptr(arg0: const_ptr[uv_fs_t]) -> ptr[void]
external function uv_fs_get_path(arg0: const_ptr[uv_fs_t]) -> cstr
external function uv_fs_get_statbuf(arg0: ptr[uv_fs_t]) -> ptr[uv_stat_t]
external function uv_fs_req_cleanup(req: ptr[uv_fs_t]) -> void
external function uv_fs_close(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], file: int, cb: uv_fs_cb?) -> int
external function uv_fs_open(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, flags_: int, mode: int, cb: uv_fs_cb?) -> int
external function uv_fs_read(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], file: int, bufs: const_ptr[uv_buf_t], nbufs: uint, offset: ptr_int, cb: uv_fs_cb?) -> int
external function uv_fs_unlink(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_write(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], file: int, bufs: const_ptr[uv_buf_t], nbufs: uint, offset: ptr_int, cb: uv_fs_cb?) -> int
external function uv_fs_copyfile(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, new_path: cstr, flags_: int, cb: uv_fs_cb?) -> int
external function uv_fs_mkdir(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, mode: int, cb: uv_fs_cb?) -> int
external function uv_fs_mkdtemp(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], tpl: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_mkstemp(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], tpl: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_rmdir(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_scandir(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, flags_: int, cb: uv_fs_cb?) -> int
external function uv_fs_scandir_next(req: ptr[uv_fs_t], ent: ptr[uv_dirent_t]) -> int
external function uv_fs_opendir(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_readdir(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], dir: ptr[uv_dir_t], cb: uv_fs_cb?) -> int
external function uv_fs_closedir(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], dir: ptr[uv_dir_t], cb: uv_fs_cb?) -> int
external function uv_fs_stat(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_fstat(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], file: int, cb: uv_fs_cb?) -> int
external function uv_fs_rename(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, new_path: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_fsync(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], file: int, cb: uv_fs_cb?) -> int
external function uv_fs_fdatasync(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], file: int, cb: uv_fs_cb?) -> int
external function uv_fs_ftruncate(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], file: int, offset: ptr_int, cb: uv_fs_cb?) -> int
external function uv_fs_sendfile(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], out_fd: int, in_fd: int, in_offset: ptr_int, length: ptr_uint, cb: uv_fs_cb?) -> int
external function uv_fs_access(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, mode: int, cb: uv_fs_cb?) -> int
external function uv_fs_chmod(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, mode: int, cb: uv_fs_cb?) -> int
external function uv_fs_utime(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, atime: double, mtime: double, cb: uv_fs_cb?) -> int
external function uv_fs_futime(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], file: int, atime: double, mtime: double, cb: uv_fs_cb?) -> int
external function uv_fs_lutime(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, atime: double, mtime: double, cb: uv_fs_cb?) -> int
external function uv_fs_lstat(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_link(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, new_path: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_symlink(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, new_path: cstr, flags_: int, cb: uv_fs_cb?) -> int
external function uv_fs_readlink(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_realpath(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, cb: uv_fs_cb?) -> int
external function uv_fs_fchmod(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], file: int, mode: int, cb: uv_fs_cb?) -> int
external function uv_fs_chown(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, uid: uint, gid: uint, cb: uv_fs_cb?) -> int
external function uv_fs_fchown(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], file: int, uid: uint, gid: uint, cb: uv_fs_cb?) -> int
external function uv_fs_lchown(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, uid: uint, gid: uint, cb: uv_fs_cb?) -> int
external function uv_fs_statfs(loop: ptr[uv_loop_t]?, req: ptr[uv_fs_t], path: cstr, cb: uv_fs_cb?) -> int

flags uv_fs_event: int
    UV_RENAME = 1
    UV_CHANGE = 2

struct uv_fs_event_s = c"uv_fs_event_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_fs_event_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    path: ptr[char]
    cb: fn(arg0: ptr[uv_fs_event_t], arg1: cstr, arg2: int, arg3: int) -> void
    watchers: uv__queue
    wd: int

struct uv_fs_poll_s = c"uv_fs_poll_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_fs_poll_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    poll_ctx: ptr[void]

external function uv_fs_poll_init(loop: ptr[uv_loop_t], handle: ptr[uv_fs_poll_t]) -> int
external function uv_fs_poll_start(handle: ptr[uv_fs_poll_t], poll_cb: fn(arg0: ptr[uv_fs_poll_t], arg1: int, arg2: const_ptr[uv_stat_t], arg3: const_ptr[uv_stat_t]) -> void, path: cstr, interval: uint) -> int
external function uv_fs_poll_stop(handle: ptr[uv_fs_poll_t]) -> int
external function uv_fs_poll_getpath(handle: ptr[uv_fs_poll_t], buffer: ptr[char], size: ptr[ptr_uint]) -> int

struct uv_signal_s = c"uv_signal_t":
    data: ptr[void]
    loop: ptr[uv_loop_t]
    type_: uv_handle_type
    close_cb: fn(arg0: ptr[uv_handle_t]) -> void
    handle_queue: uv__queue
    u: uv_signal_s_u
    next_closing: ptr[uv_handle_t]
    flags_: uint
    signal_cb: fn(arg0: ptr[uv_signal_t], arg1: int) -> void
    signum: int
    tree_entry: uv_signal_s_tree_entry
    caught_signals: uint
    dispatched_signals: uint

external function uv_signal_init(loop: ptr[uv_loop_t], handle: ptr[uv_signal_t]) -> int
external function uv_signal_start(handle: ptr[uv_signal_t], signal_cb: fn(arg0: ptr[uv_signal_t], arg1: int) -> void, signum: int) -> int
external function uv_signal_start_oneshot(handle: ptr[uv_signal_t], signal_cb: fn(arg0: ptr[uv_signal_t], arg1: int) -> void, signum: int) -> int
external function uv_signal_stop(handle: ptr[uv_signal_t]) -> int
external function uv_loadavg(avg: ptr[double]) -> void

flags uv_fs_event_flags: int
    UV_FS_EVENT_WATCH_ENTRY = 1
    UV_FS_EVENT_STAT = 2
    UV_FS_EVENT_RECURSIVE = 4

external function uv_fs_event_init(loop: ptr[uv_loop_t], handle: ptr[uv_fs_event_t]) -> int
external function uv_fs_event_start(handle: ptr[uv_fs_event_t], cb: fn(arg0: ptr[uv_fs_event_t], arg1: cstr, arg2: int, arg3: int) -> void, path: cstr, flags_: uint) -> int
external function uv_fs_event_stop(handle: ptr[uv_fs_event_t]) -> int
external function uv_fs_event_getpath(handle: ptr[uv_fs_event_t], buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_ip4_addr(ip: cstr, port: int, addr: ptr[sockaddr_in]) -> int
external function uv_ip6_addr(ip: cstr, port: int, addr: ptr[sockaddr_in6]) -> int
external function uv_ip4_name(src: const_ptr[sockaddr_in], dst: ptr[char], size: ptr_uint) -> int
external function uv_ip6_name(src: const_ptr[sockaddr_in6], dst: ptr[char], size: ptr_uint) -> int
external function uv_ip_name(src: const_ptr[sockaddr], dst: ptr[char], size: ptr_uint) -> int
external function uv_inet_ntop(af: int, src: const_ptr[void], dst: ptr[char], size: ptr_uint) -> int
external function uv_inet_pton(af: int, src: cstr, dst: ptr[void]) -> int

struct uv_random_s = c"uv_random_t":
    data: ptr[void]
    type_: uv_req_type
    reserved: array[ptr[void], 6]
    loop: ptr[uv_loop_t]
    status: int
    buf: ptr[void]
    buflen: ptr_uint
    cb: fn(arg0: ptr[uv_random_t], arg1: int, arg2: ptr[void], arg3: ptr_uint) -> void
    work_req: uv__work

external function uv_random(loop: ptr[uv_loop_t], req: ptr[uv_random_t], buf: ptr[void], buflen: ptr_uint, flags_: uint, cb: fn(arg0: ptr[uv_random_t], arg1: int, arg2: ptr[void], arg3: ptr_uint) -> void) -> int
external function uv_if_indextoname(ifindex: uint, buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_if_indextoiid(ifindex: uint, buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_exepath(buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_cwd(buffer: ptr[char], size: ptr[ptr_uint]) -> int
external function uv_chdir(dir: cstr) -> int
external function uv_get_free_memory() -> ulong
external function uv_get_total_memory() -> ulong
external function uv_get_constrained_memory() -> ulong
external function uv_get_available_memory() -> ulong
external function uv_clock_gettime(clock_id: uv_clock_id, ts: ptr[uv_timespec64_t]) -> int
external function uv_hrtime() -> ulong
external function uv_sleep(msec: uint) -> void
external function uv_disable_stdio_inheritance() -> void
external function uv_dlopen(filename: cstr, lib: ptr[uv_lib_t]) -> int
external function uv_dlclose(lib: ptr[uv_lib_t]) -> void
external function uv_dlsym(lib: ptr[uv_lib_t], name: cstr, ptr: ptr[ptr[void]]) -> int
external function uv_dlerror(lib: const_ptr[uv_lib_t]) -> cstr?
external function uv_mutex_init(handle: ptr[uv_mutex_t]) -> int
external function uv_mutex_init_recursive(handle: ptr[uv_mutex_t]) -> int
external function uv_mutex_destroy(handle: ptr[uv_mutex_t]) -> void
external function uv_mutex_lock(handle: ptr[uv_mutex_t]) -> void
external function uv_mutex_trylock(handle: ptr[uv_mutex_t]) -> int
external function uv_mutex_unlock(handle: ptr[uv_mutex_t]) -> void
external function uv_rwlock_init(rwlock: ptr[uv_rwlock_t]) -> int
external function uv_rwlock_destroy(rwlock: ptr[uv_rwlock_t]) -> void
external function uv_rwlock_rdlock(rwlock: ptr[uv_rwlock_t]) -> void
external function uv_rwlock_tryrdlock(rwlock: ptr[uv_rwlock_t]) -> int
external function uv_rwlock_rdunlock(rwlock: ptr[uv_rwlock_t]) -> void
external function uv_rwlock_wrlock(rwlock: ptr[uv_rwlock_t]) -> void
external function uv_rwlock_trywrlock(rwlock: ptr[uv_rwlock_t]) -> int
external function uv_rwlock_wrunlock(rwlock: ptr[uv_rwlock_t]) -> void
external function uv_sem_init(sem: ptr[uv_sem_t], value: uint) -> int
external function uv_sem_destroy(sem: ptr[uv_sem_t]) -> void
external function uv_sem_post(sem: ptr[uv_sem_t]) -> void
external function uv_sem_wait(sem: ptr[uv_sem_t]) -> void
external function uv_sem_trywait(sem: ptr[uv_sem_t]) -> int
external function uv_cond_init(cond: ptr[uv_cond_t]) -> int
external function uv_cond_destroy(cond: ptr[uv_cond_t]) -> void
external function uv_cond_signal(cond: ptr[uv_cond_t]) -> void
external function uv_cond_broadcast(cond: ptr[uv_cond_t]) -> void
external function uv_barrier_init(barrier: ptr[uv_barrier_t], count: uint) -> int
external function uv_barrier_destroy(barrier: ptr[uv_barrier_t]) -> void
external function uv_barrier_wait(barrier: ptr[uv_barrier_t]) -> int
external function uv_cond_wait(cond: ptr[uv_cond_t], mutex: ptr[uv_mutex_t]) -> void
external function uv_cond_timedwait(cond: ptr[uv_cond_t], mutex: ptr[uv_mutex_t], timeout: ptr_uint) -> int
external function uv_once(guard: ptr[uv_once_t], callback: fn() -> void) -> void
external function uv_key_create(key: ptr[uv_key_t]) -> int
external function uv_key_delete(key: ptr[uv_key_t]) -> void
external function uv_key_get(key: ptr[uv_key_t]) -> ptr[void]?
external function uv_key_set(key: ptr[uv_key_t], value: ptr[void]) -> void
external function uv_gettimeofday(tv: ptr[uv_timeval64_t]) -> int

type uv_thread_cb = fn(arg0: ptr[void]) -> void

external function uv_thread_create(tid: ptr[uv_thread_t], entry: fn(arg0: ptr[void]) -> void, arg: ptr[void]) -> int
external function uv_thread_detach(tid: ptr[uv_thread_t]) -> int

flags uv_thread_create_flags: int
    UV_THREAD_NO_FLAGS = 0
    UV_THREAD_HAS_STACK_SIZE = 1

struct uv_thread_options_t:
    flags_: uint
    stack_size: ptr_uint

external function uv_thread_create_ex(tid: ptr[uv_thread_t], params: const_ptr[uv_thread_options_t], entry: fn(arg0: ptr[void]) -> void, arg: ptr[void]) -> int
external function uv_thread_setaffinity(tid: ptr[uv_thread_t], cpumask: ptr[char], oldmask: ptr[char], mask_size: ptr_uint) -> int
external function uv_thread_getaffinity(tid: ptr[uv_thread_t], cpumask: ptr[char], mask_size: ptr_uint) -> int
external function uv_thread_getcpu() -> int
external function uv_thread_self() -> uv_thread_t
external function uv_thread_join(tid: ptr[uv_thread_t]) -> int
external function uv_thread_equal(t1: const_ptr[uv_thread_t], t2: const_ptr[uv_thread_t]) -> int
external function uv_thread_setname(name: cstr) -> int
external function uv_thread_getname(tid: ptr[uv_thread_t], name: ptr[char], size: ptr_uint) -> int

union uv_any_handle = c"union uv_any_handle":
    async_: uv_async_s
    check: uv_check_s
    fs_event: uv_fs_event_s
    fs_poll: uv_fs_poll_s
    handle: uv_handle_s
    idle: uv_idle_s
    pipe: uv_pipe_s
    poll: uv_poll_s
    prepare: uv_prepare_s
    process: uv_process_s
    stream: uv_stream_s
    tcp: uv_tcp_s
    timer: uv_timer_s
    tty: uv_tty_s
    udp: uv_udp_s
    signal: uv_signal_s

union uv_any_req = c"union uv_any_req":
    req: uv_req_s
    connect: uv_connect_s
    write: uv_write_s
    shutdown: uv_shutdown_s
    udp_send: uv_udp_send_s
    fs: uv_fs_s
    work: uv_work_s
    getaddrinfo: uv_getaddrinfo_s
    getnameinfo: uv_getnameinfo_s
    random: uv_random_s

struct uv_loop_s = c"uv_loop_t":
    data: ptr[void]
    active_handles: uint
    handle_queue: uv__queue
    active_reqs: uv_loop_s_active_reqs
    internal_fields: ptr[void]
    stop_flag: uint
    flags_: ptr_uint
    backend_fd: int
    pending_queue: uv__queue
    watcher_queue: uv__queue
    watchers: ptr[ptr[uv__io_t]]
    nwatchers: uint
    nfds: uint
    wq: uv__queue
    wq_mutex: pthread_mutex_t
    wq_async: uv_async_s
    cloexec_lock: pthread_rwlock_t
    closing_handles: ptr[uv_handle_t]
    process_handles: uv__queue
    prepare_handles: uv__queue
    check_handles: uv__queue
    idle_handles: uv__queue
    async_handles: uv__queue
    async_unused: fn() -> void
    async_io_watcher: uv__io_s
    async_wfd: int
    timer_heap: uv_loop_s_timer_heap
    timer_counter: ptr_uint
    time: ptr_uint
    signal_pipefd: array[int, 2]
    signal_io_watcher: uv__io_s
    child_watcher: uv_signal_s
    emfile_fd: int
    inotify_read_watcher: uv__io_s
    inotify_watchers: ptr[void]
    inotify_fd: int

external function uv_loop_get_data(arg0: const_ptr[uv_loop_t]) -> ptr[void]?
external function uv_loop_set_data(arg0: ptr[uv_loop_t], data: ptr[void]) -> void
external function uv_utf16_length_as_wtf8(utf16: const_ptr[ushort], utf16_len: ptr_int) -> ptr_uint
external function uv_utf16_to_wtf8(utf16: const_ptr[ushort], utf16_len: ptr_int, wtf8_ptr: ptr[ptr[char]], wtf8_len_ptr: ptr[ptr_uint]) -> int
external function uv_wtf8_length_as_utf16(wtf8: cstr) -> ptr_int
external function uv_wtf8_to_utf16(wtf8: cstr, utf16: ptr[ushort], utf16_len: ptr_uint) -> void

const UV__EOF: int = -4095
const UV__UNKNOWN: int = -4094
const UV__EAI_ADDRFAMILY: int = -3000
const UV__EAI_AGAIN: int = -3001
const UV__EAI_BADFLAGS: int = -3002
const UV__EAI_CANCELED: int = -3003
const UV__EAI_FAIL: int = -3004
const UV__EAI_FAMILY: int = -3005
const UV__EAI_MEMORY: int = -3006
const UV__EAI_NODATA: int = -3007
const UV__EAI_NONAME: int = -3008
const UV__EAI_OVERFLOW: int = -3009
const UV__EAI_SERVICE: int = -3010
const UV__EAI_SOCKTYPE: int = -3011
const UV__EAI_BADHINTS: int = -3013
const UV__EAI_PROTOCOL: int = -3014

external function UV__ERR() -> int

const UV__ECHARSET: int = -4080
const UV__EFTYPE: int = -4028
const UV_VERSION_MAJOR: int = 1
const UV_VERSION_MINOR: int = 52
const UV_VERSION_PATCH: int = 1
const UV_VERSION_IS_RELEASE: int = 1
const UV_FS_O_DIRECT: int = 16384
const UV_FS_O_EXLOCK: int = 0
const UV_FS_O_NOATIME: int = 0
const UV_FS_O_SYMLINK: int = 0
const UV_FS_O_FILEMAP: int = 0
const UV_FS_O_RANDOM: int = 0
const UV_FS_O_SHORT_LIVED: int = 0
const UV_FS_O_SEQUENTIAL: int = 0
const UV_FS_O_TEMPORARY: int = 0
const UV_PRIORITY_LOW: int = 19
const UV_PRIORITY_BELOW_NORMAL: int = 10
const UV_PRIORITY_NORMAL: int = 0
const UV_PRIORITY_ABOVE_NORMAL: int = -7
const UV_PRIORITY_HIGH: int = -14
const UV_PRIORITY_HIGHEST: int = -20
const UV_FS_COPYFILE_EXCL: int = 1
const UV_FS_COPYFILE_FICLONE: int = 2
const UV_FS_COPYFILE_FICLONE_FORCE: int = 4
const UV_FS_SYMLINK_DIR: int = 1
const UV_FS_SYMLINK_JUNCTION: int = 2
