# generated by mtc bindgen from /home/teefan/Projects/Ruby/mt-lang/third_party/raylib-upstream/examples/core/msf_gif.h
extern module std.c.msf_gif:
    include "msf_gif.h"

    struct MsfGifResult:
        data: ptr[void]
        dataSize: u64
        allocSize: u64
        contextPointer: ptr[void]

    struct MsfCookedFrame:
        pixels: ptr[u32]
        depth: i32
        count: i32
        rbits: i32
        gbits: i32
        bbits: i32

    struct MsfGifBuffer:
        next: ptr[MsfGifBuffer]
        size: u64
        data: array[u8, 1]

    type MsfGifFileWriteFunc = fn(arg0: ptr[void], arg1: usize, arg2: usize, arg3: ptr[void]) -> usize

    struct MsfGifState:
        fileWriteFunc: fn(arg0: ptr[void], arg1: usize, arg2: usize, arg3: ptr[void]) -> usize
        fileWriteData: ptr[void]
        previousFrame: MsfCookedFrame
        currentFrame: MsfCookedFrame
        lzwMem: ptr[i16]
        listHead: ptr[MsfGifBuffer]
        listTail: ptr[MsfGifBuffer]
        width: i32
        height: i32
        customAllocatorContext: ptr[void]
        framesSubmitted: i32

    extern def msf_gif_begin(handle: ptr[MsfGifState], width: i32, height: i32) -> i32

    extern def msf_gif_frame(handle: ptr[MsfGifState], pixelData: ptr[u8], centiSecondsPerFame: i32, maxBitDepth: i32, pitchInBytes: i32) -> i32

    extern def msf_gif_end(handle: ptr[MsfGifState]) -> MsfGifResult

    extern def msf_gif_free(result: MsfGifResult) -> void

    extern def msf_gif_begin_to_file(handle: ptr[MsfGifState], width: i32, height: i32, func: fn(arg0: ptr[void], arg1: usize, arg2: usize, arg3: ptr[void]) -> usize, filePointer: ptr[void]) -> i32

    extern def msf_gif_frame_to_file(handle: ptr[MsfGifState], pixelData: ptr[u8], centiSecondsPerFame: i32, maxBitDepth: i32, pitchInBytes: i32) -> i32

    extern def msf_gif_end_to_file(handle: ptr[MsfGifState]) -> i32
