# generated by mtc bindgen from /home/teefan/Projects/Ruby/mt-lang/third_party/raylib-upstream/examples/shaders/rlights.h
extern module std.c.rlights:
    import std.c.raylib as rl
    link "raylib"
    include "raylib.h"
    include "rlights.h"

    struct Light:
        kind: int
        enabled: bool
        position: rl.Vector3
        target: rl.Vector3
        color: rl.Color
        attenuation: float
        enabledLoc: int
        typeLoc: int
        positionLoc: int
        targetLoc: int
        colorLoc: int
        attenuationLoc: int

    flags LightType: int
        LIGHT_DIRECTIONAL = 0
        LIGHT_POINT = 1

    extern def CreateLight(kind: int, position: rl.Vector3, target: rl.Vector3, color: rl.Color, shader: rl.Shader) -> Light
    extern def UpdateLightValues(shader: rl.Shader, light: Light) -> void

    const MAX_LIGHTS: int = 4
