# generated by mtc bindgen from /home/teefan/Projects/Ruby/mt-lang/third_party/rpng-upstream/src/rpng.h
external

include "rpng.h"

struct rpng_chunk:
    length: int
    type_: array[char, 4]
    data: ptr[char]
    crc: uint

struct rpng_color:
    r: ubyte
    g: ubyte
    b: ubyte
    a: ubyte

struct rpng_palette:
    color_count: int
    colors: ptr[rpng_color]

external function rpng_load_image(filename: cstr, width: ptr[int], height: ptr[int], color_channels: ptr[int], bit_depth: ptr[int]) -> ptr[char]
external function rpng_load_image_indexed(filename: cstr, width: ptr[int], height: ptr[int], palette: ptr[rpng_palette]) -> ptr[char]
external function rpng_save_image(filename: cstr, data: cstr, width: int, height: int, color_channels: int, bit_depth: int) -> int
external function rpng_save_image_indexed(filename: cstr, indexed_data: cstr, width: int, height: int, palette: rpng_palette) -> int
external function rpng_load_image_from_memory(buffer: cstr, width: ptr[int], height: ptr[int], color_channels: ptr[int], bit_depth: ptr[int]) -> ptr[char]
external function rpng_load_image_indexed_from_memory(buffer: cstr, width: ptr[int], height: ptr[int], palette: ptr[rpng_palette]) -> ptr[char]
external function rpng_save_image_to_memory(data: cstr, width: int, height: int, color_channels: int, bit_depth: int, output_size: ptr[int]) -> ptr[char]
external function rpng_save_image_indexed_to_memory(indexed_data: cstr, width: int, height: int, palette: rpng_palette, output_size: ptr[int]) -> ptr[char]
external function rpng_unindex_image_data(indexed_data: ptr[char], width: int, height: int, palette: rpng_palette) -> ptr[char]
external function rpng_chunk_count(filename: cstr) -> int
external function rpng_chunk_read(filename: cstr, chunk_type: cstr) -> rpng_chunk
external function rpng_chunk_read_all(filename: cstr, count: ptr[int]) -> ptr[rpng_chunk]
external function rpng_chunk_remove(filename: cstr, chunk_type: cstr) -> void
external function rpng_chunk_remove_ancillary(filename: cstr) -> void
external function rpng_chunk_write(filename: cstr, data: rpng_chunk) -> void
external function rpng_chunk_write_text(filename: cstr, keyword: ptr[char], text: ptr[char]) -> void
external function rpng_chunk_write_comp_text(filename: cstr, keyword: ptr[char], text: ptr[char]) -> void
external function rpng_chunk_write_gamma(filename: cstr, gamma: float) -> void
external function rpng_chunk_write_srgb(filename: cstr, srgb_type: char) -> void
external function rpng_chunk_write_time(filename: cstr, year: short, month: char, day: char, hour: char, min: char, sec: char) -> void
external function rpng_chunk_write_physical_size(filename: cstr, pixels_unit_x: int, pixels_unit_y: int, meters: bool) -> void
external function rpng_chunk_write_chroma(filename: cstr, white_x: float, white_y: float, red_x: float, red_y: float, green_x: float, green_y: float, blue_x: float, blue_y: float) -> void
external function rpng_chunk_print_info(filename: cstr) -> void
external function rpng_chunk_check_all_valid(filename: cstr) -> bool
external function rpng_chunk_combine_image_data(filename: cstr) -> void
external function rpng_chunk_split_image_data(filename: cstr, split_size: int) -> void
external function rpng_chunk_count_from_memory(buffer: cstr) -> int
external function rpng_chunk_read_from_memory(buffer: cstr, chunk_type: cstr) -> rpng_chunk
external function rpng_chunk_read_all_from_memory(buffer: cstr, count: ptr[int]) -> ptr[rpng_chunk]
external function rpng_chunk_remove_from_memory(buffer: cstr, chunk_type: cstr, output_size: ptr[int]) -> ptr[char]
external function rpng_chunk_remove_ancillary_from_memory(buffer: cstr, output_size: ptr[int]) -> ptr[char]
external function rpng_chunk_write_from_memory(buffer: cstr, chunk: rpng_chunk, output_size: ptr[int]) -> ptr[char]
external function rpng_chunk_combine_image_data_from_memory(buffer: ptr[char], output_size: ptr[int]) -> ptr[char]
external function rpng_chunk_split_image_data_from_memory(buffer: ptr[char], split_size: int, output_size: ptr[int]) -> ptr[char]

const RPNG_MAX_CHUNKS_COUNT: int = 64
const RPNG_COMPRESSION_LEVEL: int = 8
const RPNG_SUCCESS: int = 0
const RPNG_ERROR_FILE_OPEN: int = 1
const RPNG_ERROR_PIXEL_FORMAT: int = 2
const RPNG_ERROR_MEMORY_ALLOC: int = 3
