# generated by mtc bindgen from /home/teefan/Projects/Ruby/mt-lang/std/c/string_bindgen.h
external

include "string_bindgen.h"

external function mt_string_memcpy(destination: ptr[void], source: const_ptr[void], size_bytes: ptr_uint) -> ptr[void]
external function mt_string_memmove(destination: ptr[void], source: const_ptr[void], size_bytes: ptr_uint) -> ptr[void]
external function mt_string_memset(destination: ptr[void], value: int, size_bytes: ptr_uint) -> ptr[void]
external function mt_string_memcmp(left: const_ptr[void], right: const_ptr[void], size_bytes: ptr_uint) -> int
external function mt_string_memchr(source: const_ptr[void], value: int, size_bytes: ptr_uint) -> ptr[void]?
external function mt_string_strlen(text: cstr) -> ptr_uint
external function mt_string_strcmp(left: cstr, right: cstr) -> int
external function mt_string_strncmp(left: cstr, right: cstr, size_bytes: ptr_uint) -> int
external function mt_string_strchr(text: cstr, value: int) -> ptr[char]?
external function mt_string_strrchr(text: cstr, value: int) -> ptr[char]?
external function mt_string_strstr(haystack: cstr, needle: cstr) -> ptr[char]?
